Repository xodio/xod, pull requests merged in 2018-06, with the labels that each got.

#1268 Make port type color green
  packages/xod-client/src/core/styles/abstracts/variables.scss
Labels: s:client, t:tweak

#1269 Remove obsolete tutorials
  docs/tutorial/data-types-and-conversions/README.md
  docs/tutorial/data-types-and-conversions/lcd-inspector.png
  docs/tutorial/data-types-and-conversions/ldr-led-lcd.fz.png
  docs/tutorial/data-types-and-conversions/ldr-led-lcd.fzz
  docs/tutorial/data-types-and-conversions/ldr-led-lcd.patch.png
  docs/tutorial/data-types-and-conversions/ldr-led.fz.png
  docs/tutorial/data-types-and-conversions/ldr-led.fzz
  docs/tutorial/data-types-and-conversions/ldr-led.patch.png
  docs/tutorial/data-types-and-conversions/pot-led.fz.png
  docs/tutorial/data-types-and-conversions/pot-led.fzz
  docs/tutorial/data-types-and-conversions/pot-led.patch.png
  docs/tutorial/nodes-and-links/README.md
  docs/tutorial/nodes-and-links/blink-disjoint-labeled.patch.png
  docs/tutorial/nodes-and-links/blink-disjoint.patch.png
  docs/tutorial/nodes-and-links/blink-two-leds-inv.patch.png
  docs/tutorial/nodes-and-links/blink-two-leds.patch.png
  docs/tutorial/nodes-and-links/blink.patch.png
  docs/tutorial/nodes-and-links/inspector-label.png
  docs/tutorial/nodes-and-links/inspector.png
  docs/tutorial/nodes-and-links/led-on-pin-13-and-12.fz.png
  docs/tutorial/nodes-and-links/led-on-pin-13-and-12.fzz
  docs/tutorial/nodes-and-links/led-on-pin-13.fz.png
  docs/tutorial/nodes-and-links/led-on-pin-13.fzz
  docs/tutorial/nodes-and-links/project-browser.png
  docs/tutorial/patch-nodes/README.md
  docs/tutorial/patch-nodes/guide.svg
  docs/tutorial/patch-nodes/plant-terminals-labeled.patch.png
  docs/tutorial/patch-nodes/plant-terminals.patch.png
  docs/tutorial/patch-nodes/plant.patch.png
  docs/tutorial/patch-nodes/single-plant-percent.patch.png
  docs/tutorial/patch-nodes/single-plant-with-patch-nodes.patch.png
  docs/tutorial/patch-nodes/single-plant.fz.png
  docs/tutorial/patch-nodes/single-plant.fzz
  docs/tutorial/patch-nodes/single-plant.patch.png
  docs/tutorial/patch-nodes/two-plants-main.patch.png
  docs/tutorial/patch-nodes/two-plants.fz.png
  docs/tutorial/patch-nodes/two-plants.fzz
  workspace/arduino-starter-kit/02-spaceship-interface/patch.xodp
  workspace/arduino-starter-kit/03-love-o-meter/patch.xodp
  workspace/arduino-starter-kit/04-color-mixing-lamp/patch.xodp
  workspace/arduino-starter-kit/05-mood-cue/patch.xodp
  workspace/arduino-starter-kit/main/patch.xodp
  workspace/arduino-starter-kit/project.xod
  workspace/doc-tutorial/dtc-ldr-led-lcd/patch.xodp
  workspace/doc-tutorial/dtc-ldr-led/patch.xodp
  workspace/doc-tutorial/dtc-pot-led/patch.xodp
  workspace/doc-tutorial/main/patch.xodp
  workspace/doc-tutorial/nl-blink-disjoint-labeled/patch.xodp
  workspace/doc-tutorial/nl-blink-disjoint/patch.xodp
  workspace/doc-tutorial/nl-blink-two-leds-inv/patch.xodp
  workspace/doc-tutorial/nl-blink-two-leds/patch.xodp
  workspace/doc-tutorial/pn-plant-terminals-labeled/patch.xodp
  workspace/doc-tutorial/pn-plant-terminals/patch.xodp
  workspace/doc-tutorial/pn-plant/patch.xodp
  workspace/doc-tutorial/pn-single-plant-percent/patch.xodp
  workspace/doc-tutorial/pn-single-plant-with-patch-nodes/patch.xodp
  workspace/doc-tutorial/pn-single-plant/patch.xodp
  workspace/doc-tutorial/pn-two-plants-main/patch.xodp
  workspace/doc-tutorial/project.xod
Labels: s:doc, t:chore

#1273 Fix bad literal value for i2c/request, input N
  workspace/__lib__/xod/i2c/request/patch.xodp
Labels: s:stdlib, t:bug

#1277 Upgrade puppeteer to v1.4.0
  package.json
  packages/xod-client-browser/benchmark/index.js
  packages/xod-client-browser/package.json
  packages/xod-client-browser/test-func/bootstrap.js
  packages/xod-client-browser/test-func/pageObjects/ConfirmationPopup.js
  packages/xod-client-browser/test-func/pageObjects/EditorTab.js
  packages/xod-client-browser/test-func/pageObjects/Menubar.js
  packages/xod-client-browser/test-func/pageObjects/PatchGroupItem.js
  packages/xod-client-browser/test-func/pageObjects/PatchGroupItemContextMenu.js
  packages/xod-client-browser/test-func/pageObjects/ProjectBrowser.js
  yarn.lock
Labels: s:infra, t:chore

#1276 Update screenshots for guide
  docs/guide/analog-sensor-node/step1.patch.png
  docs/guide/analog-sensor-node/step2a.patch.png
  docs/guide/analog-sensor-node/step3a.patch.png
  docs/guide/analog-sensor-node/step3b.patch.png
  docs/guide/analog-sensor-node/update-screenshots.sh
  docs/guide/cpp-state/outline.patch.png
  docs/guide/cpp-state/update-screenshots.sh
  docs/guide/cpp-time/cpp-time.xodball
  docs/guide/cpp-time/outline.patch.png
  docs/guide/cpp-time/test.patch.png
  docs/guide/cpp-time/update-screenshots.sh
  docs/guide/creating-generics/abstract.patch.png
  docs/guide/creating-generics/composition.patch.png
  docs/guide/creating-generics/terminals.patch.png
  docs/guide/creating-generics/update-screenshots.sh
  docs/guide/creating-variadics/assignments.patch.png
  docs/guide/creating-variadics/update-screenshots.sh
  docs/guide/custom-types/format-iso-example.patch.png
  docs/guide/custom-types/format-iso.patch.png
  docs/guide/custom-types/pack.patch.png
  docs/guide/custom-types/time.patch.png
  docs/guide/custom-types/unpack-example.patch.png
  docs/guide/custom-types/unpack.patch.png
  docs/guide/custom-types/update-screenshots.sh
  docs/guide/generics/deduction.patch.png
  docs/guide/generics/if-else.patch.png
  docs/guide/generics/samples.xodball
  docs/guide/generics/update-screenshots.sh
  docs/guide/nodes-for-xod-in-cpp/step1.patch.png
  docs/guide/nodes-for-xod-in-cpp/step2.patch.png
  docs/guide/nodes-for-xod-in-cpp/update-screenshots.sh
  docs/guide/nodes-for-xod-in-xod/step1.patch.png
  docs/guide/nodes-for-xod-in-xod/step2.patch.png
  docs/guide/nodes-for-xod-in-xod/step3a.patch.png
  docs/guide/nodes-for-xod-in-xod/step3b.patch.png
  docs/guide/nodes-for-xod-in-xod/step4a.patch.png
  docs/guide/nodes-for-xod-in-xod/step4b.patch.png
  docs/guide/nodes-for-xod-in-xod/step5a.patch.png
  docs/guide/nodes-for-xod-in-xod/step5b.patch.png
  docs/guide/nodes-for-xod-in-xod/update-screenshots.sh
  docs/guide/simple-traffic-light/state-2.patch.png
  docs/guide/simple-traffic-light/traffic-light-simple.xodball
  docs/guide/simple-traffic-light/update-screenshots.sh
  docs/guide/variadics/expansion.patch.png
  docs/guide/variadics/join-expansion.patch.png
  docs/guide/variadics/overview.patch.png
  docs/guide/variadics/select-a2-expansion.patch.png
  docs/guide/variadics/select-a2.patch.png
  docs/guide/variadics/update-screenshots.sh
  tools/screenshot-xodball
  tools/update-docs-screenshots.sh
Labels: s:doc, s:infra, t:chore, t:feat

#1275 Update changelog for upcoming 0.21.0
  CHANGELOG.md
Labels: s:doc, t:chore

#1278 Release 0.21.0
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1280 Update expected dependencies list of xod/common-hardware in xod-pm func tests
  packages/xod-pm/test-func/fetch.spec.js
Labels: t:chore

#1279 Rename imported 'xod-project' from Project to XP in `xod-arduino`
  packages/xod-arduino/src/transpiler.js
Labels: s:core, t:chore

#1285 Rewrite pragma directive lookup in ReasonML
  .eslintrc.js
  .gitignore
  packages/xod-arduino/bsconfig.json
  packages/xod-arduino/package.json
  packages/xod-arduino/src/Directives.re
  packages/xod-arduino/src/Directives.rei
  packages/xod-arduino/src/Directives_Js.re
  packages/xod-arduino/src/directives.js
  packages/xod-arduino/test/directives.spec.js
  packages/xod-tabtest/package.json
  yarn.lock
Labels: s:core, t:refactor

#1290 Do not request switch workspace on any save/load error
  packages/xod-client-electron/src/view/actions.js
  packages/xod-client-electron/src/view/containers/App.jsx
Labels: t:refactor

#1298 Update expected deps list in func tests
  packages/xod-pm/test-func/fetch.spec.js
Labels: t:chore

#1296 Actualize tutorial
  docs/tutorial/01-hello/README.md
  docs/tutorial/03-inspector/README.md
  docs/tutorial/09-pot/README.md
  docs/tutorial/17-ldr/patch.png
  docs/tutorial/18-comparisons/patch.png
  docs/tutorial/19-if-else/patch.png
  docs/tutorial/21-pulses/README.md
  docs/tutorial/tutorial-update-screenshot.xodball
  packages/xod-client-electron/test-func/fixtures/welcome-to-xod.xodball
  workspace/welcome-to-xod/01-hello/patch.xodp
  workspace/welcome-to-xod/02-deploy/patch.xodp
  workspace/welcome-to-xod/03-inspector/patch.xodp
  workspace/welcome-to-xod/04-pwm/patch.xodp
  workspace/welcome-to-xod/05-wiring/patch.xodp
  workspace/welcome-to-xod/06-adding-nodes/patch.xodp
  workspace/welcome-to-xod/07-labels/patch.xodp
  workspace/welcome-to-xod/08-constants/patch.xodp
  workspace/welcome-to-xod/09-pot/patch.xodp
  workspace/welcome-to-xod/10-math/patch.xodp
  workspace/welcome-to-xod/11-servo/patch.xodp
  workspace/welcome-to-xod/12-help/patch.xodp
  workspace/welcome-to-xod/13-map/patch.xodp
  workspace/welcome-to-xod/14-map-adjust/patch.xodp
  workspace/welcome-to-xod/15-buttons/patch.xodp
  workspace/welcome-to-xod/16-logic/patch.xodp
  workspace/welcome-to-xod/17-ldr/patch.xodp
  workspace/welcome-to-xod/18-comparisons/patch.xodp
  workspace/welcome-to-xod/19-if-else/patch.xodp
  workspace/welcome-to-xod/20-fade/patch.xodp
  workspace/welcome-to-xod/21-pulses/patch.xodp
  workspace/welcome-to-xod/22-clock/patch.xodp
  workspace/welcome-to-xod/23-count/patch.xodp
  workspace/welcome-to-xod/24-flip-flop/patch.xodp
  workspace/welcome-to-xod/25-multiple-timelines/patch.xodp
  workspace/welcome-to-xod/26-lcd/patch.xodp
  workspace/welcome-to-xod/27-lcd-data/patch.xodp
  workspace/welcome-to-xod/28-string-concat/patch.xodp
Labels: hotfix, s:doc, t:bug

#1300 Release 0.21.1
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-pm/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1301 Merge 0.21.x back into master
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-arduino/platform/runtime.cpp
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-pm/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:chore

#1307 Correct output name in xod/math/clip impl
  workspace/__lib__/xod/math/clip/patch.cpp
Labels: hotfix, s:stdlib, t:bug

#1306 Do not try to extract "stale" bound values
  packages/xod-arduino/test/transpiler.spec.js
  packages/xod-project/src/extractBoundInputsToConstNodes.js
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
Labels: hotfix, s:core, t:bug, urgent

#1308 Allow constant node values to propagate down when flattening
  packages/xod-project/src/flatten.js
  packages/xod-project/test/fixtures/constant-propagation-through-bound-output.flat.xodball
  packages/xod-project/test/fixtures/constant-propagation-through-bound-output.xodball
  packages/xod-project/test/flatten.spec.js
Labels: hotfix, s:core, t:bug

#1309 Release 0.21.2
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1310 Merge 0.21.x into master
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-arduino/test/transpiler.spec.js
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-project/src/extractBoundInputsToConstNodes.js
  packages/xod-project/src/flatten.js
  packages/xod-project/test/fixtures/constant-propagation-through-bound-output.flat.xodball
  packages/xod-project/test/fixtures/constant-propagation-through-bound-output.xodball
  packages/xod-project/test/flatten.spec.js
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/clip/patch.cpp
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
Labels: t:chore
