Repository xodio/xod, pull requests merged in 2018-05, with the labels that each got.

#1194 Fix crash when constructing message about wrong variadic pin types
  packages/xod-project/src/messages.js
  packages/xod-project/src/patch.js
  packages/xod-project/test/patch.spec.js
Labels: regression, s:core, t:bug, urgent

#1196 Release 0.20.2
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1173 Adjust documentation index page look-n-feel and structure
  docs/README.md
  docs/__img__/automatic-humidifier.jpg
  docs/__img__/drone-bot-workshop.jpg
  docs/__img__/guide.svg
  docs/__img__/mert.jpg
  docs/__img__/puddin.jpg
  docs/__img__/rechargeable-solar-lamp.jpeg
  docs/__img__/reference.svg
  docs/__img__/self-driving-robot.jpeg
  docs/__img__/trash-bin.jpg
  docs/__img__/tutorial.svg
  docs/__img__/xod.jpg
  docs/guide/README.md
  docs/reference/README.md
  docs/showcase.yaml
  docs/tutorial/README.md
  docs/tutvideos.yaml
Labels: s:doc, t:tweak

#1199 Remove Travis CI traces
  .travis.yml
  README.md
  tools/extract-release-notes.js
  tools/travis.sh
Labels: s:infra, t:chore

#1202 Fix canceling of open project in browser ide causes exception
  packages/xod-client-browser/src/containers/App.jsx
Labels: s:client, t:bug

#1207 Fix bound value migration for pulses
  packages/xod-project/src/legacy.js
  packages/xod-project/test/legacy.spec.js
Labels: s:core, t:bug

#1204 Fix bug in the transpilation: wrong output pin labels
  packages/xod-arduino/src/transpiler.js
Labels: t:bug, urgent

#1209 Make contributor’s guide
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/README.md
  docs/contributing/README.md
Labels: s:doc, t:feat

#1210 Add IDE docker images building on release
  .circleci/Dockerfile
  .circleci/config.yml
  package.json
  packages/xod-client-browser/Dockerfile
  packages/xod-project/Dockerfile
Labels: s:infra, t:chore

#1213 Tweak performance of type deduction
  packages/xod-client/src/project/selectors.js
  packages/xod-func-tools/src/index.js
  packages/xod-func-tools/src/sets.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/typeDeduction.js
Labels: t:perf

#1223 Improve wording for contributing section in the docs
  .github/ISSUE_TEMPLATE.md
  docs/contributing/README.md
Labels: s:doc, t:tweak

#1214 Optimize memoized selector comparators
  packages/xod-client/src/project/selectors.js
  packages/xod-client/src/projectBrowser/selectors.js
  packages/xod-func-tools/src/objects.js
  packages/xod-func-tools/src/sets.js
  packages/xod-project/src/index.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/typeDeduction.js
  packages/xod-project/test/patch.spec.js
Labels: t:perf

#1233 Update changelog for upcoming 0.20.3
  CHANGELOG.md
Labels: hotfix

#1236 Remove leading 'v' from docker image tag
  .circleci/config.yml
Labels: s:infra, t:bug

#1238 Fix IDE crash when opening missing patch
  packages/xod-client/src/editor/actions.js
  packages/xod-client/src/project/selectors.js
  packages/xod-client/src/project/utils.js
  packages/xod-project/src/project.js
Labels: s:client, t:bug

#1250 Color conflicting pins in the Inspector
  packages/xod-client/src/core/styles/components/Pin.scss
Labels: s:client, t:tweak

#1246 Improve error message about conflicting types
  packages/xod-project/src/messages.js
  packages/xod-project/src/typeDeduction.js
Labels: s:core, t:tweak
