Repository xodio/xod, pull requests merged in 2018-04, with the labels that each got.

#1154 Fix crash when changing arity level
  packages/xod-client/src/editor/containers/Patch/modes/changingArityLevel.jsx
Labels: regression, t:bug, urgent

#1163 Fix crash on pressing undo when nothing was selected
  packages/xod-client/src/editor/reducer.js
Labels: s:client, t:bug

#1161 Add generic markers to the generic Pins
  packages/xod-client/src/core/styles/components/Pin.scss
  packages/xod-client/src/project/components/Pin.jsx
Labels: s:client, t:feat

#1167 Refactor abstract nodes resolution
  packages/xod-project/src/messages.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/project.js
  packages/xod-project/src/typeDeduction.js
  packages/xod-project/src/types.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-bound-nongenerics.xodball
  packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved-variadics.xodball
  packages/xod-project/test/fixtures/abstract-nodes-resolution.resolved.xodball
  packages/xod-project/test/fixtures/abstract-nodes-resolution.xodball
  packages/xod-project/test/patch.spec.js
  packages/xod-project/test/typeDeduction.spec.js
  packages/xod-project/test/utils.spec.js
Labels: s:core, t:refactor

#1172 Make deducePinTypes safer
  packages/xod-project/src/typeDeduction.js
Labels: s:core, t:refactor

#1176 Update changelog for upcoming 0.20.0
  CHANGELOG.md
Labels: s:infra, t:doc

#1178 Always install devDependencies in CI
  .circleci/config.yml
Labels: s:infra, t:bug, urgent

#1180 Fix crashing IDE on opening project with nodes from not installed libs
  packages/xod-project/src/project.js
Labels: regression, t:bug, urgent

#1184 Release 0.20.1
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra
