Repository xodio/xod, pull requests merged in 2018-11, with the labels that each got.

#1496 Make xod/core/clock tick even if EN is always dirty
  workspace/__lib__/xod/core/clock/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/firmware.bin
  workspace/blink/__fixtures__/firmware.hex
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
Labels: s:stdlib, t:bug

#1524 xod/bits/shift-* works with int32_t
  workspace/__lib__/xod/bits/shift-left/patch.cpp
  workspace/__lib__/xod/bits/shift-left/patch.test.tsv
  workspace/__lib__/xod/bits/shift-left/patch.xodp
  workspace/__lib__/xod/bits/shift-right/patch.cpp
  workspace/__lib__/xod/bits/shift-right/patch.test.tsv
  workspace/__lib__/xod/bits/shift-right/patch.xodp
Labels: hotfix

#1535 Switch circleci macOS image to xcode 10; Switch to yarn 1.10.1
  .circleci/Dockerfile
  .circleci/config.yml
  yarn.lock
Labels: s:infra, t:chore

#1533 Prevent sidebar scroll position jumps
  packages/xod-client/package.json
  yarn.lock
Labels: s:client, t:bug

#1534 Better error reporting in xod/common-hardware/sd-log
  workspace/__lib__/xod/common-hardware/sd-log/patch.cpp
Labels: s:stdlib, t:tweak

#1542 Cherry pick hotfixes from master to 0.25.x
  .circleci/Dockerfile
  .circleci/config.yml
  packages/xod-client/package.json
  packages/xod-client/src/editor/messages.js
  workspace/__lib__/xod/common-hardware/sd-log/patch.cpp
  yarn.lock
Labels: t:chore

#1549 Prevent autoupdate on not supported platforms
  packages/xod-client-electron/src/app/main.js
Labels: s:client, t:bug

#1531 Improve tabtests engine, cover `xod/math` with tabtests and fix/add some nodes
  packages/xod-tabtest/cpp/Arduino.h
  packages/xod-tabtest/src/TabData.re
  packages/xod-tabtest/src/TabData.rei
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/test/TabData_jest.re
  workspace/__lib__/xod/math/abs/patch.test.tsv
  workspace/__lib__/xod/math/acos/patch.test.tsv
  workspace/__lib__/xod/math/asin/patch.test.tsv
  workspace/__lib__/xod/math/atan/patch.test.tsv
  workspace/__lib__/xod/math/ceil/patch.test.tsv
  workspace/__lib__/xod/math/clip/patch.test.tsv
  workspace/__lib__/xod/math/cos/patch.test.tsv
  workspace/__lib__/xod/math/cube/patch.test.tsv
  workspace/__lib__/xod/math/discretize/patch.test.tsv
  workspace/__lib__/xod/math/discretize/patch.xodp
  workspace/__lib__/xod/math/floor/patch.test.tsv
  workspace/__lib__/xod/math/is-finite/patch.cpp
  workspace/__lib__/xod/math/is-finite/patch.test.tsv
  workspace/__lib__/xod/math/is-finite/patch.xodp
  workspace/__lib__/xod/math/is-nan/patch.cpp
  workspace/__lib__/xod/math/is-nan/patch.test.tsv
  workspace/__lib__/xod/math/is-nan/patch.xodp
  workspace/__lib__/xod/math/log-10/patch.test.tsv
  workspace/__lib__/xod/math/log-bx/patch.test.tsv
  workspace/__lib__/xod/math/log-e/patch.test.tsv
  workspace/__lib__/xod/math/map-clip/patch.test.tsv
  workspace/__lib__/xod/math/map/patch.cpp
  workspace/__lib__/xod/math/map/patch.test.tsv
  workspace/__lib__/xod/math/pi/patch.test.tsv
  workspace/__lib__/xod/math/pow/patch.test.tsv
  workspace/__lib__/xod/math/round/patch.test.tsv
  workspace/__lib__/xod/math/sin/patch.test.tsv
  workspace/__lib__/xod/math/sqrt/patch.test.tsv
  workspace/__lib__/xod/math/square/patch.test.tsv
  workspace/__lib__/xod/math/tan/patch.test.tsv
Labels: s:stdlib, t:chore, t:tweak

#1536 xod-cli: tabtests in separate directories, clean before run
  .circleci/config.yml
  packages/xod-cli/src/commands/tabtest.js
  packages/xod-cli/test/tabtest.spec.js
Labels: s:cli, t:feat, wip

#1544 Support XStrings in tabtests and make bulletproof `formatNumber`
  cpplib/catch2utils/XStringFormat.inl
  packages/xod-arduino/platform/formatNumber.h
  packages/xod-arduino/platform/listFuncs.h
  packages/xod-arduino/platform/runtime.cpp
  packages/xod-arduino/platform/types.h
  packages/xod-arduino/src/templates.js
  packages/xod-arduino/test-cpp/formatNumber.cpp
  packages/xod-arduino/tools/test-avr-size.sh
  packages/xod-arduino/tools/test-cpp.sh
  packages/xod-cli/package.json
  packages/xod-cli/src/commands/tabtest.js
  packages/xod-cli/src/paths.js
  packages/xod-deploy/test-func/cloudCompiler.spec.js
  packages/xod-tabtest/cpp/Arduino.h
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/workspace/__lib__/xod/tabtest/capture-string/patch.xodp
  tools/update-compiled-fixtures.sh
  tools/update-transpiled-fixtures.sh
  workspace/__ardulib__/ESP8266UART/ESP8266UART.h
  workspace/__lib__/xod/core/cast-number-to-string/patch.cpp
  workspace/__lib__/xod/core/cast-to-string(number)/patch.cpp
  workspace/__lib__/xod/core/cast-to-string(number)/patch.test.tsv
  workspace/__lib__/xod/core/concat/patch.test.tsv
  workspace/__lib__/xod/core/format-number/patch.cpp
  workspace/__lib__/xod/core/format-number/patch.test.tsv
  workspace/__lib__/xod/core/gate(string)/patch.test.tsv
  workspace/__lib__/xod/core/if-else(string)/patch.test.tsv
  workspace/__lib__/xod/core/length(string)/patch.test.tsv
  workspace/__lib__/xod/core/pad-with-zeroes/patch.cpp
  workspace/__lib__/xod/core/pad-with-zeroes/patch.test.tsv
  workspace/blink/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/firmware.bin
  workspace/blink/__fixtures__/firmware.hex
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:core, t:feat

#1548 New xod-cli commands and new package xod-deploy-bin
  packages/arduino-cli/package.json
  packages/arduino-cli/src/index.js
  packages/arduino-cli/src/parseProgressLog.js
  packages/arduino-cli/test-func/mocha.opts
  packages/xod-cli/README.md
  packages/xod-cli/package.json
  packages/xod-cli/src/baseCommand.js
  packages/xod-cli/src/commands/boards.js
  packages/xod-cli/src/commands/compile.js
  packages/xod-cli/src/commands/install/arch.js
  packages/xod-cli/src/commands/tabtest.js
  packages/xod-cli/src/commands/transpile.js
  packages/xod-cli/src/commands/upload.js
  packages/xod-cli/src/flags.js
  packages/xod-cli/src/listrTasks.js
  packages/xod-cli/src/messages.js
  packages/xod-cli/test-func/boards.spec.js
  packages/xod-cli/test-func/compile-upload.spec.js
  packages/xod-cli/test-func/help.spec.js
  packages/xod-cli/test-func/helpers.js
  packages/xod-cli/test-func/installArch.spec.js
  packages/xod-cli/test-func/mocha.opts
  packages/xod-cli/test-func/publish.spec.js
  packages/xod-cli/test-func/resave.spec.js
  packages/xod-cli/test-func/tabtest.spec.js
  packages/xod-cli/test-func/transpile.spec.js
  packages/xod-cli/test/help.spec.js
  packages/xod-client-browser/test-func/pageObjects/PromptPopup.js
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/app/arduinoCli.js
  packages/xod-client-electron/src/app/arduinoDependencies.js
  packages/xod-client-electron/src/app/main.js
  packages/xod-client-electron/src/app/migrateArduinoPackages.js
  packages/xod-client-electron/src/arduinoDependencies/middleware.js
  packages/xod-client-electron/src/shared/messages.js
  packages/xod-client-electron/src/upload/messages.js
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client-electron/src/view/formatError.js
  packages/xod-deploy-bin/.babelrc
  packages/xod-deploy-bin/README.md
  packages/xod-deploy-bin/package.json
  packages/xod-deploy-bin/src/arduinoCli.js
  packages/xod-deploy-bin/src/constants.js
  packages/xod-deploy-bin/src/index.js
  packages/xod-deploy-bin/src/messages.js
  yarn.lock
Labels: s:cli, s:client, t:feat, t:refactor

#1558 Update arduino cli to 0.3.2
  .circleci/config.yml
  tools/install-arduinocli.ps1
Labels: hotfix

#1554 Fix "Select All" hotkey in Desktop IDE
  packages/xod-client-electron/src/view/containers/App.jsx
Labels: s:client, t:bug

#1560 Use fixed in PR arduino-cli version of 0.3.2
  .circleci/config.yml
  tools/install-arduinocli.ps1
Labels: hotfix, s:client

#1556 Improve undo/redo hotkeys reliability
  packages/xod-client-browser/package.json
  packages/xod-client-browser/src/containers/App.jsx
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client/package.json
  packages/xod-client/src/core/actions.js
  packages/xod-client/src/editor/components/LibSuggester.jsx
  packages/xod-client/src/editor/components/Suggester.jsx
  packages/xod-client/src/editor/containers/Editor.jsx
  packages/xod-client/src/utils/browser.js
  packages/xod-client/src/utils/constants.js
  yarn.lock
Labels: s:client, t:bug

#1555 Fix publisherName to match certificate's "Issued to" field
  packages/xod-client-electron/package.json
Labels: s:client, t:bug

#1557 Support pulses in tabtests
  packages/xod-arduino/tools/test-avr-size.sh
  packages/xod-tabtest/cpp/Arduino.cpp
  packages/xod-tabtest/src/TabData.re
  packages/xod-tabtest/src/TabData.rei
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/test/TabData_jest.re
  packages/xod-tabtest/workspace/__lib__/xod/tabtest/capture-pulse/patch.cpp
  packages/xod-tabtest/workspace/__lib__/xod/tabtest/capture-pulse/patch.xodp
  packages/xod-tabtest/workspace/__lib__/xod/tabtest/inject-pulse/patch.cpp
  workspace/__lib__/xod/core/boot/patch.test.tsv
  workspace/__lib__/xod/core/delta/patch.cpp
  workspace/__lib__/xod/core/delta/patch.test.tsv
  workspace/__lib__/xod/core/delta/patch.xodp
  workspace/__lib__/xod/core/flip-flop/patch.cpp
  workspace/__lib__/xod/core/flip-flop/patch.test.tsv
  workspace/__lib__/xod/core/gate(pulse)/patch.test.tsv
  workspace/__lib__/xod/core/pulse-on-change/patch.test.tsv
  workspace/__lib__/xod/core/pulse-on-false/patch.test.tsv
  workspace/__lib__/xod/core/pulse-on-true/patch.test.tsv
  workspace/blink/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/firmware.hex
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:feat

#1566 Release 0.25.3
  CHANGELOG.md
  lerna.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1567 Support mocking time flow for tabtests
  packages/xod-tabtest/cpp/Arduino.cpp
  packages/xod-tabtest/cpp/Arduino.h
  packages/xod-tabtest/src/TabData.re
  packages/xod-tabtest/src/TabData.rei
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/test/TabData_jest.re
  workspace/__lib__/xod/core/clock/patch.test.tsv
  workspace/__lib__/xod/core/continuously-pausable/patch.test.tsv
  workspace/__lib__/xod/core/continuously/patch.test.tsv
  workspace/__lib__/xod/core/delay/patch.test.tsv
  workspace/__lib__/xod/core/delta-time/patch.test.tsv
  workspace/__lib__/xod/core/delta-time/patch.xodp
  workspace/__lib__/xod/core/delta/patch.cpp
  workspace/__lib__/xod/core/delta/patch.test.tsv
  workspace/__lib__/xod/core/delta/patch.xodp
  workspace/__lib__/xod/core/fade/patch.test.tsv
  workspace/__lib__/xod/core/system-time/patch.test.tsv
Labels: t:feat

#1574 Fix workspace creation
  packages/xod-cli/test-func/mocha.opts
  packages/xod-client-electron/src/app/main.js
  packages/xod-deploy-bin/src/arduinoCli.js
Labels: t:bug

#1568 Add missing formatter for error about too many outputs
  packages/xod-arduino/src/index.js
  packages/xod-arduino/src/messages.js
  packages/xod-arduino/src/transpiler.js
  packages/xod-arduino/test/transpiler.spec.js
  packages/xod-client/src/core/formatErrorMessage.js
Labels: s:client, t:bug

#1571 Support comments in tabtests
  packages/xod-tabtest/src/TabData.re
  packages/xod-tabtest/test/TabData_jest.re
Labels: t:feat

#1578 Add missing xod/core node descriptions
  workspace/__lib__/xod/core/constant-boolean/patch.xodp
  workspace/__lib__/xod/core/constant-byte/patch.xodp
  workspace/__lib__/xod/core/constant-number/patch.xodp
  workspace/__lib__/xod/core/constant-port/patch.xodp
  workspace/__lib__/xod/core/constant-string/patch.xodp
  workspace/__lib__/xod/core/length(string)/patch.xodp
  workspace/__lib__/xod/core/sine-wave/patch.xodp
  workspace/__lib__/xod/core/square-wave/patch.xodp
Labels: s:stdlib, t:doc

#1581 Tweak Installing Packages UX
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
  packages/xod-client-electron/src/upload/reducer.js
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client/src/core/assets/fonts/noto-emoji.woff
  packages/xod-client/src/core/assets/fonts/noto-emoji.woff2
  packages/xod-client/src/core/styles/abstracts/variables.scss
  packages/xod-client/src/core/styles/base/base.scss
  packages/xod-client/src/core/styles/fonts/noto-emoji.scss
  packages/xod-client/src/core/styles/main.scss
  packages/xod-client/src/debugger/constants.js
  packages/xod-client/src/debugger/reducer.js
  packages/xod-client/src/index.js
Labels: s:client, t:tweak
