Repository xodio/xod, pull requests merged in 2018-08, with the labels that each got.

#1395 Load built-in patches from a special .xodball instead of generating them programmatically
  packages/xod-patch-search/test/index.spec.js
  packages/xod-project/built-in-patches.xodball
  packages/xod-project/package.json
  packages/xod-project/src/builtinTerminalPatches.js
  packages/xod-project/src/constants.js
  packages/xod-project/src/flatten.js
  packages/xod-project/src/index.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/project.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/project.spec.js
  packages/xod-project/test/utils.spec.js
  packages/xod-project/tools/loadBuiltinPatches.js
  packages/xod-project/tools/makeDummyBuiltinPatches.js
  workspace/__lib__/xod/core/jumper/patch.xodp
Labels: s:core, t:refactor

#1398 Fix rebuilding of xod-project
  packages/xod-project/tools/makeDummyBuiltinPatches.js
Labels: s:infra, t:bug

#1401 Fix displaying pins with conflicting types as custom
  packages/xod-client/src/project/utils.js
Labels: regression, s:client

#1403 Refmt all reason files
  packages/holes/src/Holes_List.rei
  packages/holes/src/Holes_Option.re
  packages/holes/src/Holes_Option.rei
  packages/holes/test/Holes_List_jest.re
  packages/xod-arduino/src/Directives.re
  packages/xod-arduino/src/Directives.rei
  packages/xod-arduino/src/Directives_Js.re
  packages/xod-arduino/src/Transpiler.re
  packages/xod-arduino/src/Transpiler.rei
  packages/xod-func-tools/src/Either.re
  packages/xod-func-tools/src/Maybe.re
  packages/xod-project/src/Buses.re
  packages/xod-project/src/Buses.rei
  packages/xod-project/src/Node.re
  packages/xod-project/src/Patch.re
  packages/xod-project/src/Pin.rei
  packages/xod-project/src/Position.re
  packages/xod-project/src/Project.re
  packages/xod-project/src/TypeDeduction.re
  packages/xod-project/src/TypeDeduction.rei
  packages/xod-project/src/TypeDeduction_Js.re
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/src/Tabtest.rei
  packages/xod-tabtest/src/Tabtest_Js.re
  packages/xod-tabtest/src/XodFS/Loader.re
  packages/xod-tabtest/src/XodFS/Loader.rei
Labels: t:chore

#1400 Improve performance of `xod-patch-search`
  packages/xod-patch-search/src/index.js
Labels: t:perf

#1404 Optimize patch search and suggester
  packages/xod-client/src/editor/components/Suggester.jsx
  packages/xod-client/src/editor/containers/Editor.jsx
  packages/xod-client/src/hinting/actionType.js
  packages/xod-client/src/hinting/actionTypes.js
  packages/xod-client/src/hinting/actionUtils.js
  packages/xod-client/src/hinting/actions.js
  packages/xod-client/src/hinting/errorCollectors.js
  packages/xod-client/src/hinting/middleware.js
  packages/xod-client/src/hinting/patchSearchData.js
  packages/xod-client/src/hinting/reducer.js
  packages/xod-client/src/hinting/selectors.js
  packages/xod-client/src/hinting/state.js
  packages/xod-client/src/hinting/typeDeduction.js
  packages/xod-client/src/hinting/validation.internal.js
  packages/xod-client/src/hinting/validation.js
  packages/xod-client/src/project/actions.js
  packages/xod-client/src/project/reducer.js
  packages/xod-client/src/project/selectors.js
  packages/xod-client/test/hinting.spec.js
  packages/xod-patch-search/src/index.js
  packages/xod-patch-search/test/index.spec.js
  packages/xod-project/src/node.js
Labels: t:perf

#1408 Fix error hinting on bus label change
  packages/xod-client/src/hinting/validation.js
  packages/xod-project/src/internal/patchPathUtils.js
  packages/xod-project/src/patchPathUtils.js
Labels: t:bug, urgent

#1407 Make possible to reopen project with the same file path in browser IDE
  packages/xod-client-browser/src/containers/App.jsx
Labels: s:client, t:bug

#1411 Release 0.23.0
  CHANGELOG.md
  lerna.json
  packages/holes/package.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1413 Fix library version bumper
  tools/bump-workspace-lib-versions.sh
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
Labels: s:infra

#1424 Merge fixes from 0.23.x into master
  packages/xod-client/src/core/styles/components/Node.scss
  packages/xod-client/src/core/styles/components/TabsItem.scss
  packages/xod-client/src/hinting/patchSearchData.js
Labels: t:chore
