Repository xodio/xod, pull requests merged in 2018-10, with the labels that each got.

#1456 ESP8266 compatibility
  packages/xod-arduino/platform/memory.h
  packages/xod-tabtest/cpp/Arduino.h
  workspace/__lib__/xod-dev/esp8266-mcu/close/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/close/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/connect/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/connect/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/esp8266-mcu-device/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/esp8266-mcu-device/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/esp8266-mcu-inet/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/esp8266-mcu-inet/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/example-get-data-from-dweet/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/example-get-external-ip/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/http-request(esp8266-mcu-inet)/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/is-open/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/is-open/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/lan-ip/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/lan-ip/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/open-tcp/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/open-tcp/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/read-byte/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/read-byte/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/receive/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/send/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/send/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/socket/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/socket/patch.xodp
  workspace/__lib__/xod-dev/esp8266/connect-wifi/patch.xodp
  workspace/__lib__/xod-dev/esp8266/connect/patch.xodp
  workspace/__lib__/xod/core/pad-with-zeroes/patch.cpp
  workspace/__lib__/xod/gpio/pwm-write/patch.cpp
  workspace/__lib__/xod/uart/soft-uart/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:rt/c++, s:stdlib, t:feat

#1460 Stop checking if port is less than zero
  workspace/__lib__/xod/common-hardware/servo/patch.cpp
  workspace/__lib__/xod/gpio/digital-read/patch.cpp
  workspace/__lib__/xod/gpio/digital-write/patch.cpp
  workspace/__lib__/xod/gpio/pwm-write/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
Labels: s:stdlib, t:tweak

#1463 Make xod-dev/esp8266-mcu/example-get-external-ip more clear
  workspace/__lib__/xod-dev/esp8266-mcu/example-get-external-ip/patch.xodp
Labels: s:stdlib, t:tweak

#1464 Make nodes for DHT11 and DHT2x more robust
  workspace/__lib__/xod/common-hardware/dhtxx-read-raw/patch.cpp
Labels: s:stdlib, t:bug

#1462 Make possible to upload on esp8266
  .circleci/config.yml
  packages/arduino-cli/README.md
  packages/arduino-cli/src/cpuParser.js
  packages/arduino-cli/src/index.js
  packages/arduino-cli/src/optionParser.js
  packages/arduino-cli/src/parseTable.js
  packages/arduino-cli/test-func/index.spec.js
  packages/arduino-cli/test/cpuParser.spec.js
  packages/arduino-cli/test/fixtures/packages/arduino/hardware/avr/1.6.21/boards.txt
  packages/arduino-cli/test/fixtures/packages/esp8266/hardware/esp8266/2.4.2/boards.txt
  packages/arduino-cli/test/mocha.opts
  packages/arduino-cli/test/optionParser.spec.js
  packages/arduino-cli/test/parseTable.spec.js
  packages/xod-client-electron/src/app/arduinoCli.js
  packages/xod-client-electron/src/app/constants.js
  packages/xod-client-electron/src/arduinoDependencies/messages.js
  packages/xod-client-electron/src/shared/messages.js
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
  packages/xod-client-electron/src/upload/messages.js
  packages/xod-client-electron/src/upload/reducer.js
  packages/xod-client-electron/src/upload/selectors.js
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client-electron/webpack.config.js
  packages/xod-client/src/core/styles/components/Button.scss
  packages/xod-client/src/core/styles/components/SkyLight.scss
  packages/xod-client/src/core/styles/components/SnackBarList.scss
  packages/xod-client/src/core/styles/components/UploadPopup.scss
  packages/xod-client/src/core/styles/main.scss
  tools/install-arduinocli.ps1
  workspace/__packages__/package_esp8266com_index.json
Labels: t:feat

#1466 Make http-request(esp8266-mcu) more resillient
  workspace/__lib__/xod-dev/esp8266-mcu/http-request(esp8266-mcu-inet)/patch.xodp
Labels: s:stdlib, t:tweak

#1470 Correctly induce variadic labels for pins with numeric labels
  packages/xod-project/src/pin.js
  packages/xod-project/test/pin.spec.js
Labels: s:core, t:bug

#1473 Release 0.25.0
  CHANGELOG.md
  lerna.json
  packages/belt-holes/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1474 Provide default name for xodball saved from browser IDE
  packages/xod-client-browser/src/containers/App.jsx
Labels: s:client, t:tweak

#1482 Do not rely on NUM_DIGITAL_PINS being defined
  packages/xod-arduino/platform/runtime.cpp
  packages/xod-tabtest/cpp/Arduino.h
  workspace/__lib__/xod/common-hardware/servo/patch.cpp
  workspace/__lib__/xod/gpio/analog-read/patch.cpp
  workspace/__lib__/xod/gpio/digital-read/patch.cpp
  workspace/__lib__/xod/gpio/digital-write/patch.cpp
  workspace/__lib__/xod/gpio/pwm-write/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:bug

#1475 Change arduino-cli config on switch workspace
  packages/arduino-cli/README.md
  packages/arduino-cli/src/config.js
  packages/arduino-cli/src/index.js
  packages/arduino-cli/test-func/index.spec.js
  packages/xod-client-electron/src/app/arduinoCli.js
  packages/xod-client-electron/src/app/main.js
  packages/xod-client-electron/src/app/migrateArduinoPackages.js
Labels: s:client, t:bug

#1487 Release 0.25.1
  CHANGELOG.md
  lerna.json
  packages/arduino-cli/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1495 Make xod/core/buffer generic
  workspace/__lib__/xod/core/buffer/patch.xodp
Labels: s:stdlib, t:tweak

#1508 Fix port validation false negatives
  packages/xod-arduino/platform/runtime.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/firmware.bin
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:rt/c++, t:bug

#1507 Don't raise DTR when opening serialport on windows
  packages/xod-deploy/src/serialport.js
Labels: s:client, t:bug

#1520 Create buses from links leading to variadic pins
  packages/xod-project/src/Buses.re
  packages/xod-project/src/Patch.re
  packages/xod-project/src/Patch.rei
  packages/xod-project/src/index.js
  packages/xod-project/test/fixtures/jumperize.expected.xodball
  packages/xod-project/test/fixtures/jumperize.xodball
  packages/xod-project/test/fixtures/split-links-to-buses.expected.xodball
  packages/xod-project/test/fixtures/split-links-to-buses.xodball
Labels: s:client, s:core, t:bug

#1512 Make sure generated C++ is compatible with STM32 boards
  packages/xod-arduino/platform/runtime.cpp
  packages/xod-client/src/utils/normalizePort.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/utils.spec.js
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:client, s:rt/c++

#1522 Add missing labels for variadic pins in Inspector
  packages/xod-client/src/editor/components/NodeInspector.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/BoolPinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/DisabledInputWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/GenericPinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/NumberPinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PulsePinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
Labels: s:client, t:bug
