Repository xodio/xod, pull requests merged in 2018-03, with the labels that each got.

#1095 Implement xod/core/join
  workspace/__lib__/xod/core/join/patch.xodp
Labels: s:stdlib, t:feat

#1094 Don’t show tooltip for dragged node
  packages/xod-client/src/project/components/Node.jsx
  packages/xod-client/src/tooltip/components/Tooltip.jsx
Labels: s:client, t:tweak

#1098 Fix tutorial node labels
  docs/tutorial/10-math/README.md
  docs/tutorial/10-math/patch.png
  docs/tutorial/10-math/screencast.gif
  docs/tutorial/16-logic/README.md
  docs/tutorial/16-logic/patch.png
  docs/tutorial/18-comparisons/README.md
  docs/tutorial/18-comparisons/patch.png
  docs/tutorial/18-comparisons/screencast.gif
  docs/tutorial/28-string-concat/README.md
  docs/tutorial/28-string-concat/patch.png
  docs/tutorial/28-string-concat/screencast.gif
  packages/xod-client-electron/test-func/fixtures/welcome-to-xod.xodball
  workspace/__lib__/xod/core/absolute/patch.cpp
  workspace/__lib__/xod/core/absolute/patch.xodp
  workspace/__lib__/xod/core/ceil/patch.cpp
  workspace/__lib__/xod/core/ceil/patch.xodp
  workspace/__lib__/xod/core/divide/patch.cpp
  workspace/__lib__/xod/core/divide/patch.xodp
  workspace/__lib__/xod/core/equal/patch.cpp
  workspace/__lib__/xod/core/equal/patch.xodp
  workspace/__lib__/xod/core/floor/patch.cpp
  workspace/__lib__/xod/core/floor/patch.xodp
  workspace/__lib__/xod/core/greater/patch.cpp
  workspace/__lib__/xod/core/greater/patch.xodp
  workspace/__lib__/xod/core/less/patch.cpp
  workspace/__lib__/xod/core/less/patch.xodp
  workspace/__lib__/xod/core/not/patch.cpp
  workspace/__lib__/xod/core/not/patch.xodp
  workspace/__lib__/xod/core/round/patch.cpp
  workspace/__lib__/xod/core/round/patch.xodp
  workspace/__lib__/xod/core/subtract/patch.cpp
  workspace/__lib__/xod/core/subtract/patch.xodp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/welcome-to-xod/10-math/patch.xodp
  workspace/welcome-to-xod/16-logic/patch.xodp
  workspace/welcome-to-xod/18-comparisons/patch.xodp
  workspace/welcome-to-xod/28-string-concat/patch.xodp
Labels: s:stdlib, t:doc, t:tweak

#1097 Update changelog for upcoming 0.19.0
  CHANGELOG.md
Labels: t:doc

#1100 Show if a pin is variadic in help panel
  packages/xod-client/src/core/styles/components/PatchDocs.scss
  packages/xod-client/src/editor/components/PatchDocs.jsx
  packages/xod-client/stories/PatchDocs.jsx
Labels: s:client, t:tweak

#1103 Release 0.19.0
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/core/project.xod
Labels: t:chore

#1104 Make clarification for variadics article
  docs/guide/creating-variadics/README.md
Labels: t:doc, t:tweak

#1106 Remove unneeded output pin from xod/core/discretize
  workspace/__lib__/xod/core/discretize/patch.xodp
  workspace/__lib__/xod/core/project.xod
Labels: s:stdlib, t:tweak

#1107 Add CI steps that check for side-effects after build/tests
  .circleci/config.yml
Labels: s:infra, t:tweak

#1108 Do not emit extraneous pulse from defer-pulse on boot
  workspace/__lib__/xod/core/defer-pulse/patch.cpp
Labels: regression, s:stdlib, t:bug

#1111 Сheck for dead links more strictly
  packages/xod-project/src/patch.js
Labels: s:core, t:bug

#1113 Release 0.19.2
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1115 Add a tool to bump all core lib versions
  tools/bump-workspace-lib-versions.sh
Labels: s:infra

#1120 Allow to relink occupied input pins
  packages/xod-client/src/core/styles/components/Pin.scss
  packages/xod-client/src/editor/actions.js
  packages/xod-client/src/editor/constants.js
  packages/xod-client/src/editor/containers/Patch/index.jsx
  packages/xod-client/src/project/actions.js
  packages/xod-client/src/project/components/Pin.jsx
  packages/xod-client/src/project/messages.js
  packages/xod-client/src/project/reducer.js
  packages/xod-client/src/project/utils.js
  packages/xod-client/test/project.spec.js
  packages/xod-client/test/reducers/editor.spec.js
  packages/xod-project/src/link.js
Labels: s:client, t:tweak

#1135 Support 700px IDE window width
  packages/xod-client-electron/src/app/main.js
  packages/xod-client/src/core/styles/components/Suggester.scss
  packages/xod-client/src/editor/containers/Helpbox.jsx
Labels: s:client, t:tweak

#1136 Use parametric patch names for cast and defer nodes
  package.json
  packages/xod-arduino/src/transpiler.js
  packages/xod-client-browser/benchmark/getDurations.js
  packages/xod-client-browser/benchmark/index.js
  packages/xod-client-browser/tools/loadTutorialProject.js
  packages/xod-client-browser/tools/staticServer.js
  packages/xod-fs/src/utils.js
  packages/xod-project/src/constants.js
  packages/xod-project/src/patchPathUtils.js
  packages/xod-project/src/types.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/fixtures/blinking.flat.xodball
  packages/xod-project/test/fixtures/blinking.xodball
  packages/xod-project/test/fixtures/cast-multiple-outputs.flat.xodball
  packages/xod-project/test/fixtures/cast-multiple-outputs.xodball
  packages/xod-project/test/fixtures/deep-bound-values-propagation.flat.xodball
  packages/xod-project/test/fixtures/deep-bound-values-propagation.xodball
  packages/xod-project/test/flatten.spec.js
  packages/xod-project/test/patchPathUtils.spec.js
  tools/electron-upload.js
  tools/extract-release-notes.js
  workspace/__lib__/xod/core/cast(boolean,number)/patch.cpp
  workspace/__lib__/xod/core/cast(boolean,number)/patch.xodp
  workspace/__lib__/xod/core/cast(boolean,pulse)/patch.cpp
  workspace/__lib__/xod/core/cast(boolean,pulse)/patch.xodp
  workspace/__lib__/xod/core/cast(boolean,string)/patch.cpp
  workspace/__lib__/xod/core/cast(boolean,string)/patch.xodp
  workspace/__lib__/xod/core/cast(number,boolean)/patch.cpp
  workspace/__lib__/xod/core/cast(number,boolean)/patch.xodp
  workspace/__lib__/xod/core/cast(number,string)/patch.cpp
  workspace/__lib__/xod/core/cast(number,string)/patch.xodp
  workspace/__lib__/xod/core/defer(boolean)/patch.cpp
  workspace/__lib__/xod/core/defer(boolean)/patch.xodp
  workspace/__lib__/xod/core/defer(number)/patch.cpp
  workspace/__lib__/xod/core/defer(number)/patch.xodp
  workspace/__lib__/xod/core/defer(pulse)/patch.cpp
  workspace/__lib__/xod/core/defer(pulse)/patch.xodp
  workspace/__lib__/xod/core/defer(string)/patch.cpp
  workspace/__lib__/xod/core/defer(string)/patch.xodp
  workspace/__lib__/xod/core/defer/patch.xodp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/main/patch.xodp
  workspace/lcd-time/__fixtures__/arduino.cpp
Labels: s:core, s:stdlib, t:feat

#1145 Remove kludge for installing react-autosuggest
  .circleci/config.yml
  lerna.json
  packages/xod-client/package.json
  yarn.lock
Labels: s:infra, t:chore
