Repository xodio/xod, pull requests merged in 2018-12, with the labels that each got.

#1582 update catch2 and fix tabtest namespacing
  packages/xod-tabtest/cpp/main.cpp
  packages/xod-tabtest/src/Tabtest.re
  vendor/catch2/catch.hpp
Labels: t:tweak

#1592 Fix hanging upload process on error
  packages/xod-client-electron/src/view/containers/App.jsx
Labels: regression, s:client, t:bug, urgent

#1595 Add timeout pin to `xod-dev/esp8266-mcu/connect`
  workspace/__lib__/xod-dev/esp8266-mcu/connect/patch.cpp
  workspace/__lib__/xod-dev/esp8266-mcu/connect/patch.xodp
  workspace/__lib__/xod-dev/esp8266-mcu/example-get-external-ip/patch.xodp
Labels: s:stdlib, t:tweak

#1601 Fix closing of Switch Workspace Popup and click outside the popup
  packages/xod-client-electron/src/settings/components/PopupSetWorkspace.jsx
  packages/xod-client/src/core/styles/components/SkyLight.scss
Labels: s:client, t:bug

#1599 Tweak double click on constant nodes
  packages/xod-client/package.json
  packages/xod-client/src/core/domSideeffectsMiddleware.js
  packages/xod-client/src/core/middlewares.js
  packages/xod-client/src/editor/actionTypes.js
  packages/xod-client/src/editor/actions.js
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/StringPinWidget.jsx
  packages/xod-client/src/editor/containers/Patch/index.jsx
  packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
  packages/xod-client/src/editor/reducer.js
  yarn.lock
Labels: s:client, t:tweak

#1604 Update changelog for upcoming 0.26.0
  CHANGELOG.md
Labels: t:chore

#1605 Release 0.26.0
  CHANGELOG.md
  lerna.json
  packages/arduino-cli/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-tabtest/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1606 Fix readme generation in xod-cli
  .prettierignore
  packages/xod-cli/README.md
  packages/xod-cli/package.json
Labels: s:cli, t:chore

#1610 Prepare arduino-cli wrapper for publishing
  packages/arduino-cli/package.json
Labels: t:chore

#1619 Update changelog for upcoming 0.26.1
  CHANGELOG.md
Labels: s:doc
