Repository xodio/xod, pull requests merged in 2018-07, with the labels that each got.

#1313 Make normalizeByte reject invalid integer values
  packages/xod-client/src/utils/normalizeByte.js
  packages/xod-client/test/normalizeByte.spec.js
Labels: s:client, t:tweak

#1320 Correct reference to divide node in xod/math/log-bx
  workspace/__lib__/xod/math/log-bx/patch.xodp
Labels: regression, s:stdlib, t:bug

#1314 Make computation of bounding boxes safer
  packages/xod-client/src/editor/utils.js
  packages/xod-client/src/project/nodeLayout.js
Labels: s:client, t:bug

#1326 Add missing descriptions for nodes in xod-dev/w5500, xod/net and xod/stream
  workspace/__lib__/xod-dev/w5500/close/patch.cpp
  workspace/__lib__/xod-dev/w5500/close/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-manual/patch.cpp
  workspace/__lib__/xod-dev/w5500/connect-manual/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect/patch.cpp
  workspace/__lib__/xod-dev/w5500/connect/patch.xodp
  workspace/__lib__/xod-dev/w5500/ethernet-shield-device/patch.xodp
  workspace/__lib__/xod-dev/w5500/has-available-byte/patch.xodp
  workspace/__lib__/xod-dev/w5500/http-request(inet)/patch.xodp
  workspace/__lib__/xod-dev/w5500/inet/patch.xodp
  workspace/__lib__/xod-dev/w5500/is-open/patch.xodp
  workspace/__lib__/xod-dev/w5500/lan-ip/patch.xodp
  workspace/__lib__/xod-dev/w5500/open-tcp/patch.xodp
  workspace/__lib__/xod-dev/w5500/read-byte/patch.xodp
  workspace/__lib__/xod-dev/w5500/receive/patch.xodp
  workspace/__lib__/xod-dev/w5500/send/patch.cpp
  workspace/__lib__/xod-dev/w5500/send/patch.xodp
  workspace/__lib__/xod/net/format-http-request/patch.xodp
  workspace/__lib__/xod/net/format-ip/patch.xodp
  workspace/__lib__/xod/net/ip-address/patch.xodp
  workspace/__lib__/xod/net/ip-to-octets/patch.xodp
  workspace/__lib__/xod/net/mac-address/patch.xodp
  workspace/__lib__/xod/net/socket/patch.xodp
  workspace/__lib__/xod/stream/accumulate-string/patch.xodp
  workspace/__lib__/xod/stream/parse-integer/patch.xodp
  workspace/__lib__/xod/stream/pass-from-sequence/patch.xodp
  workspace/__lib__/xod/stream/pass-if/patch.xodp
  workspace/__lib__/xod/stream/pass-until/patch.xodp
  workspace/__lib__/xod/stream/pulse-on-sequence/patch.xodp
  workspace/__lib__/xod/stream/skip-until/patch.xodp
Labels: s:stdlib, t:doc

#1317 Char literal for byte type
  docs/reference/data-types/README.md
  packages/xod-arduino/src/templates.js
  packages/xod-client/src/utils/normalizeByte.js
  packages/xod-client/test/normalizeByte.spec.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/utils.spec.js
Labels: s:client, s:core, t:feat

#1331 Always mark pins of custom type as not bindable
  packages/xod-project/src/patch.js
Labels: s:core, t:bug

#1333 Fix typos in xod-dev/w5500
  workspace/__lib__/xod-dev/w5500/example-get-your-ip/patch.xodp
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/w5500/send/patch.cpp
Labels: s:stdlib, t:bug, t:tweak

#1334 Fix tracking of unsaved changes in desktop IDE
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client/src/core/trackLastSavedChanges.js
Labels: regression, s:client

#1341 Defer blocking `connect-*` nodes by default in xod-dev/w5500
  workspace/__lib__/xod-dev/w5500/connect-blocking/patch.cpp
  workspace/__lib__/xod-dev/w5500/connect-blocking/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-manual-blocking/patch.cpp
  workspace/__lib__/xod-dev/w5500/connect-manual-blocking/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-manual/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect/patch.xodp
  workspace/__lib__/xod-dev/w5500/example-get-data-from-dweet/patch.xodp
  workspace/__lib__/xod-dev/w5500/example-get-your-ip/patch.xodp
Labels: s:stdlib, t:tweak

#1343 Run type deduction on found specializations in case they use generic nodes
  packages/xod-project/src/typeDeduction.js
  packages/xod-project/test/fixtures/custom-types.resolved.xodball
  packages/xod-project/test/fixtures/custom-types.xodball
Labels: s:core, t:bug, urgent

#1342 Add abstract http-request patches to xod/net
  workspace/__lib__/xod-dev/esp8266/close/patch.xodp
  workspace/__lib__/xod-dev/esp8266/connect/patch.xodp
  workspace/__lib__/xod-dev/esp8266/esp8266-inet/patch.cpp
  workspace/__lib__/xod-dev/esp8266/esp8266-inet/patch.xodp
  workspace/__lib__/xod-dev/esp8266/example-get-ips/patch.xodp
  workspace/__lib__/xod-dev/esp8266/http-request(esp8266-inet)/patch.xodp
  workspace/__lib__/xod-dev/esp8266/is-open/patch.xodp
  workspace/__lib__/xod-dev/esp8266/lan-ip/patch.xodp
  workspace/__lib__/xod-dev/esp8266/open-tcp/patch.xodp
  workspace/__lib__/xod-dev/esp8266/receive-one-byte/patch.xodp
  workspace/__lib__/xod-dev/esp8266/receive/patch.xodp
  workspace/__lib__/xod-dev/esp8266/send/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-blocking/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-manual-blocking/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect-manual/patch.xodp
  workspace/__lib__/xod-dev/w5500/connect/patch.xodp
  workspace/__lib__/xod-dev/w5500/ethernet-shield/patch.xodp
  workspace/__lib__/xod-dev/w5500/example-get-data-from-dweet/patch.xodp
  workspace/__lib__/xod-dev/w5500/example-get-your-ip/patch.xodp
  workspace/__lib__/xod-dev/w5500/http-request(w5500-inet)/patch.xodp
  workspace/__lib__/xod-dev/w5500/lan-ip/patch.xodp
  workspace/__lib__/xod-dev/w5500/open-tcp/patch.xodp
  workspace/__lib__/xod-dev/w5500/w5500-device/patch.cpp
  workspace/__lib__/xod-dev/w5500/w5500-device/patch.xodp
  workspace/__lib__/xod-dev/w5500/w5500-inet/patch.cpp
  workspace/__lib__/xod-dev/w5500/w5500-inet/patch.xodp
  workspace/__lib__/xod/net/http-get/patch.xodp
  workspace/__lib__/xod/net/http-post/patch.xodp
  workspace/__lib__/xod/net/http-request/patch.xodp
Labels: s:stdlib, t:feat

#1345 Remove leftover native implementation files of `connect` and `connect-manual` in xod-dev/w5500
  workspace/__lib__/xod-dev/w5500/connect-manual/patch.cpp
  workspace/__lib__/xod-dev/w5500/connect/patch.cpp
Labels: s:stdlib, t:bug

#1352 Release 0.22.0
  CHANGELOG.md
  lerna.json
  packages/xod-arduino-deploy/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: s:infra, t:chore

#1356 Detect pin name clashes
  packages/xod-arduino/src/transpiler.js
  packages/xod-client/src/editor/components/PatchDocs.jsx
  packages/xod-client/src/project/selectors.js
  packages/xod-client/src/project/utils.js
  packages/xod-project/src/index.js
  packages/xod-project/src/messages.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/pin.js
  packages/xod-project/src/project.js
  packages/xod-project/test/patch.spec.js
  packages/xod-project/test/pin.spec.js
  packages/xod-tabtest/src/XodProject/Pin.re
Labels: s:client, s:core, t:bug

#1376 Skip clashing pin labels check for expanded variadic patches
  packages/xod-project/src/internal/patchPathUtils.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/patchPathUtils.js
  packages/xod-project/test/patch.spec.js
  packages/xod-project/test/patchPathUtils.spec.js
Labels: regression, s:core

#1381 Abandon Flow
  .circleci/config.yml
  .eslintrc.js
  .flowconfig
  README.md
  flow-typed/npm/ramda_v0.x.x.js
  package.json
  yarn.lock
Labels: s:infra, t:chore

#1386 Get rid of React warning in DebuggerTopPane
  packages/xod-client/src/debugger/containers/DebuggerTopPane.jsx
Labels: s:client, t:bug
