Repository xodio/xod, pull requests merged in 2019-04, with the labels that each got.

#1738 Add the rest of `tweak-string` nodes
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/src/templates.js
  workspace/__lib__/xod/debug/tweak-string-128/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-128/patch.xodp
  workspace/__lib__/xod/debug/tweak-string-32/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-32/patch.xodp
  workspace/__lib__/xod/debug/tweak-string-64/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-64/patch.xodp
Labels: s:rt/c++, s:stdlib, t:feat

#1736 Allow custom name of wasm file
  packages/xod-client/src/workers/wasm.worker.js
Labels: s:client, t:bug

#1735 First chapter of the updated tutorial
  workspace/welcome-to-xod/001-hello/patch.xodp
  workspace/welcome-to-xod/002-simulate/patch.xodp
  workspace/welcome-to-xod/003-inspector/patch.xodp
  workspace/welcome-to-xod/004-patching/patch.xodp
  workspace/welcome-to-xod/005-tweaks/patch.xodp
  workspace/welcome-to-xod/006-help/patch.xodp
  workspace/welcome-to-xod/007-booleans/patch.xodp
  workspace/welcome-to-xod/008-variadics/patch.xodp
  workspace/welcome-to-xod/009-pulses/patch.xodp
  workspace/welcome-to-xod/010-flip-flop/patch.xodp
  workspace/welcome-to-xod/011-if-else/patch.xodp
  workspace/welcome-to-xod/012-strings/patch.xodp
  workspace/welcome-to-xod/project.xod
Labels: s:doc

#1739 Deprecate `xod/core/word-to-number`
  workspace/__lib__/xod/core/word-to-number/patch.xodp
Labels: s:stdlib, t:tweak

#1741 Docs screenshotter auto-detects patch height if it's not specified by User
  tools/screenshot-xodball
Labels: t:chore, t:tweak

#1743 Add headings for tutorial’s first chapter
  workspace/welcome-to-xod/002-simulate/patch.xodp
  workspace/welcome-to-xod/003-inspector/patch.xodp
  workspace/welcome-to-xod/004-patching/patch.xodp
  workspace/welcome-to-xod/005-tweaks/patch.xodp
  workspace/welcome-to-xod/006-help/patch.xodp
  workspace/welcome-to-xod/007-booleans/patch.xodp
  workspace/welcome-to-xod/008-variadics/patch.xodp
  workspace/welcome-to-xod/009-pulses/patch.xodp
  workspace/welcome-to-xod/010-flip-flop/patch.xodp
  workspace/welcome-to-xod/011-branching/patch.xodp
  workspace/welcome-to-xod/012-strings/patch.xodp
Labels: s:doc, t:tweak

#1747 Merge 0.28.x into master
  .circleci/cache-version
  .circleci/config.yml
  CHANGELOG.md
  lerna.json
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
Labels: t:chore

#1745 Patch noding section of the tutorial
  workspace/welcome-to-xod/300-creating-nodes/patch.xodp
  workspace/welcome-to-xod/301-create-new-patch/patch.xodp
  workspace/welcome-to-xod/302-check-your-new-patch/patch.xodp
  workspace/welcome-to-xod/303-add-terminals/patch.xodp
  workspace/welcome-to-xod/304-use-new-node/patch.xodp
  workspace/welcome-to-xod/305-document-it/patch.xodp
  workspace/welcome-to-xod/306-next-steps/patch.xodp
  workspace/welcome-to-xod/999-the-end/patch.xodp
Labels: s:doc, t:feat

#1744 Add tool that generates tutorial docs from welcome-to-xod project
  tools/generate-tutorial-docs.js
Labels: s:infra, t:feat

#1748 Integrate @nkrkv's mutex and servo libraries in stdlib
  workspace/__lib__/xod-dev/servo/example-00-pot/patch.xodp
  workspace/__lib__/xod-dev/servo/example-10-sequence/patch.xodp
  workspace/__lib__/xod-dev/servo/example-11-sequence-reenter/patch.xodp
  workspace/__lib__/xod-dev/servo/example-20-state-sequence/patch.xodp
  workspace/__lib__/xod-dev/servo/position-value/patch.cpp
  workspace/__lib__/xod-dev/servo/position-value/patch.xodp
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/servo/rotate-slow/patch.xodp
  workspace/__lib__/xod-dev/servo/rotate/patch.cpp
  workspace/__lib__/xod-dev/servo/rotate/patch.xodp
  workspace/__lib__/xod-dev/servo/servo-device/patch.cpp
  workspace/__lib__/xod-dev/servo/servo-device/patch.xodp
  workspace/__lib__/xod-dev/servo/servo/patch.cpp
  workspace/__lib__/xod-dev/servo/servo/patch.xodp
  workspace/__lib__/xod/core/animation-segment/patch.xodp
  workspace/__lib__/xod/core/animation-unit/patch.cpp
  workspace/__lib__/xod/core/animation-unit/patch.xodp
  workspace/__lib__/xod/mutex/mutex-break/patch.cpp
  workspace/__lib__/xod/mutex/mutex-break/patch.xodp
  workspace/__lib__/xod/mutex/mutex-gate/patch.cpp
  workspace/__lib__/xod/mutex/mutex-gate/patch.xodp
  workspace/__lib__/xod/mutex/mutex-state/patch.cpp
  workspace/__lib__/xod/mutex/mutex-state/patch.xodp
  workspace/__lib__/xod/mutex/mutex/patch.cpp
  workspace/__lib__/xod/mutex/mutex/patch.xodp
  workspace/__lib__/xod/mutex/project.xod
Labels: s:stdlib, t:feat

#1751 Deprecate `xod/common-hardware/servo` in favour of `xod-dev/servo/servo`
  workspace/__lib__/xod/common-hardware/servo/patch.xodp
Labels: s:stdlib, t:refactor

#1749 Fix screenshot tools
  tools/generate-tutorial-docs.js
  tools/screenshot-xodball
Labels: s:infra, t:bug

#1750 Replace TODOs and some ports in welcome-to-xod project
  packages/xod-client-browser/test-func/deletingOpenedPatch.spec.js
  workspace/welcome-to-xod/001-hello/patch.xodp
  workspace/welcome-to-xod/006-help/patch.xodp
  workspace/welcome-to-xod/009-pulses/patch.xodp
  workspace/welcome-to-xod/012-strings/patch.xodp
  workspace/welcome-to-xod/100-hardware/patch.xodp
  workspace/welcome-to-xod/103-led/patch.xodp
  workspace/welcome-to-xod/104-button/patch.xodp
  workspace/welcome-to-xod/105-pot/patch.xodp
  workspace/welcome-to-xod/106-servo/patch.xodp
  workspace/welcome-to-xod/107-manipulator/patch.xodp
  workspace/welcome-to-xod/108-text-lcd/patch.xodp
  workspace/welcome-to-xod/109-thermometer/patch.xodp
  workspace/welcome-to-xod/110-ldr/patch.xodp
  workspace/welcome-to-xod/200-patterns/patch.xodp
  workspace/welcome-to-xod/201-matching-ranges/patch.xodp
  workspace/welcome-to-xod/202-alarm/patch.xodp
  workspace/welcome-to-xod/203-permanent-alarm/patch.xodp
  workspace/welcome-to-xod/204-run-for-x-seconds/patch.xodp
  workspace/welcome-to-xod/205-loops/patch.xodp
  workspace/welcome-to-xod/211-units-of-measure/patch.xodp
Labels: t:refactor

#1752 Mark libraries and project icons with red color if it contains errors
  packages/xod-client/src/core/assets/icons/libs-err.svg
  packages/xod-client/src/core/assets/icons/project-err.svg
  packages/xod-client/src/core/styles/components/PatchGroup.scss
  packages/xod-client/src/core/styles/components/PatchGroupItem.scss
  packages/xod-client/src/projectBrowser/components/PatchGroup.jsx
  packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
Labels: s:client, t:feat

#1746 Remove “Compile in the cloud” option from upload dialog
  packages/xod-client-electron/src/app/arduinoCli.js
  packages/xod-client-electron/src/shared/messages.js
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-deploy/src/cloudCompiler.js
  packages/xod-deploy/src/index.js
  packages/xod-deploy/src/toPio.json
  packages/xod-deploy/test-func/cloudCompiler.spec.js
Labels: s:client, t:tweak

#1754 Fix lib name for `xod/mutex`
  workspace/__lib__/xod/mutex/project.xod
Labels: s:stdlib, t:bug

#1755 Update changelog for upcoming 0.29.0
  CHANGELOG.md
Labels: s:doc

#1757 Release 0.29.0
  CHANGELOG.md
  lerna.json
  packages/belt-holes/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1756 Tweak tutorial generator tool to make correct index of exercises
  tools/generate-tutorial-docs.js
Labels: s:infra, t:tweak

#1759 Fix C++ errors/warnings in new nodes
  workspace/__lib__/xod-dev/servo/servo-device/patch.cpp
  workspace/__lib__/xod/core/animation-unit/patch.cpp
Labels: regression, s:stdlib, t:bug

#1760 Add missing descriptions to `xod-dev/servo`, `xod-mutex`, `xod-net` and `xod/stream` libraries
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
Labels: s:doc

#1761 Prevent race condition on initialisation in xod/common-hardware/st-imu-generic-sensor
  workspace/__lib__/xod/common-hardware/st-imu-generic-sensor/patch.xodp
Labels: s:stdlib, t:bug

#1763 Release 0.29.1
  CHANGELOG.md
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1765 Fix PropType in PatchGroup component
  packages/xod-client/src/projectBrowser/components/PatchGroup.jsx
Labels: s:client, t:bug

#1767 Make `xod/core/if-else` truly generic
  workspace/__lib__/xod/core/if-else(byte)/patch.xodp
  workspace/__lib__/xod/core/if-else(number)/patch.xodp
  workspace/__lib__/xod/core/if-else(string)/patch.xodp
  workspace/__lib__/xod/core/if-else/patch.cpp
  workspace/__lib__/xod/core/if-else/patch.xodp
  workspace/test/test-core/test-generc-if-else-with-booleans/patch.test.tsv
  workspace/test/test-core/test-generc-if-else-with-booleans/patch.xodp
  workspace/test/test-core/test-generc-if-else-with-bytes/patch.test.tsv
  workspace/test/test-core/test-generc-if-else-with-bytes/patch.xodp
  workspace/test/test-core/test-generc-if-else-with-numbers/patch.test.tsv
  workspace/test/test-core/test-generc-if-else-with-numbers/patch.xodp
  workspace/test/test-core/test-generc-if-else-with-strings/patch.test.tsv
  workspace/test/test-core/test-generc-if-else-with-strings/patch.xodp
Labels: s:stdlib, t:feat
