Repository xodio/xod, pull requests merged in 2019-12, with the labels that each got.

#1912 Prepare changelog for 0.32.0
  CHANGELOG.md
Labels: t:chore

#1903 Implement xod-cloud publish nodes
  workspace/__lib__/xod-cloud/feeds/cloud-store-custom/patch.xodp
  workspace/__lib__/xod-cloud/feeds/cloud-store/patch.xodp
  workspace/__lib__/xod-cloud/feeds/is-non-200-response/patch.xodp
  workspace/__lib__/xod-cloud/feeds/project.xod
Labels: s:stdlib, t:feat

#1913 Release 0.32.0
  CHANGELOG.md
  lerna.json
  packages/arduino-cli/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1914 Fix crash on sendidng tweak pulses
  packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js
  packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
Labels: hotfix, regression, t:bug

#1915 Fix implementation of the placement new operator
  packages/xod-arduino/platform/memory.h
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:bug, urgent

#1919 Merge 0.32.1 to master
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-arduino/platform/memory.h
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js
  packages/xod-client/package.json
  packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
  packages/xod-cloud-compile/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/equal(boolean)/patch.cpp
  workspace/__lib__/xod/core/equal(boolean)/patch.xodp
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:chore

#1924 Stop simulation on creating/opening project
  packages/xod-client/src/editor/stopSimulationMiddleware.js
Labels: t:bug

#1925 Do not store values for pulse inputs and outputs
  packages/xod-arduino/platform/patchContext.tpl.cpp
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/platform/types.h
  packages/xod-arduino/src/templates.js
  packages/xod-arduino/src/transpiler.js
  packages/xod-arduino/src/types.js
  packages/xod-arduino/tools/test-avr-size.sh
  packages/xod-tabtest/src/Tabtest.re
  packages/xod-tabtest/workspace/__lib__/xod/tabtest/inject-pulse/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/firmware.hex
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:rt/c++

#1926 Support hex color literals
  packages/xod-arduino/src/templates.js
  packages/xod-client/src/editor/components/inspectorWidgets/index.js
  packages/xod-client/src/editor/constants.js
  packages/xod-client/src/utils/normalizeColor.js
  packages/xod-client/test/normalizeColor.spec.js
  packages/xod-project/.babelrc
  packages/xod-project/src/builtinTerminalPatches.js
  packages/xod-project/src/constants.js
  packages/xod-project/src/custom-types.js
  packages/xod-project/src/index.js
  packages/xod-project/src/patch.js
  packages/xod-project/src/utils.js
  packages/xod-project/test/customTypeLiterals.spec.js
  packages/xod-project/test/utils.spec.js
Labels: s:client, s:core, s:rt/c++, t:feat

#1927 Add “big patch” fixture
  packages/xod-arduino/tools/test-avr-size.sh
  tools/update-transpiled-fixtures.sh
  workspace/big-patch/__fixtures__/arduino.cpp
  workspace/big-patch/alarm-sound/patch.xodp
  workspace/big-patch/main/patch.xodp
  workspace/big-patch/max-value/patch.xodp
  workspace/big-patch/panic/patch.xodp
  workspace/big-patch/play-note/patch.cpp
  workspace/big-patch/play-note/patch.xodp
  workspace/big-patch/project.xod
  workspace/big-patch/show-info/patch.xodp
Labels: t:chore

#1928 Add the XColor type structure
  packages/xod-arduino/platform/types.h
  workspace/__lib__/xod/color/color/patch.cpp
  workspace/big-patch/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: wip

#1931 Implement xod-dev/ws2812
  workspace/__ardulib__/README.md
  workspace/__ardulib__/WS2812_NoBufffer/WS2812.cpp
  workspace/__ardulib__/WS2812_NoBufffer/WS2812.h
  workspace/__ardulib__/WS2812_NoBufffer/esp8266.c
  workspace/__lib__/xod-dev/ws2812/clear/patch.cpp
  workspace/__lib__/xod-dev/ws2812/clear/patch.xodp
  workspace/__lib__/xod-dev/ws2812/example-advanced/patch.xodp
  workspace/__lib__/xod-dev/ws2812/example-quickstart/patch.xodp
  workspace/__lib__/xod-dev/ws2812/fill-solid/patch.cpp
  workspace/__lib__/xod-dev/ws2812/fill-solid/patch.xodp
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod-dev/ws2812/ws2812-device/patch.cpp
  workspace/__lib__/xod-dev/ws2812/ws2812-device/patch.xodp
  workspace/__lib__/xod-dev/ws2812/ws2812-mono/patch.xodp
  workspace/__lib__/xod/color/color/patch.cpp
  workspace/__lib__/xod/color/pulse-on-change(color)/patch.cpp
  workspace/__lib__/xod/color/pulse-on-change(color)/patch.xodp
Labels: s:stdlib
