Repository xodio/xod, pull requests merged in 2019-10, with the labels that each got.

#1868 Release 0.31.0
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1870 Tweak `xod/debug/stream-string` node
  workspace/__lib__/xod/debug/stream-string/patch.cpp
Labels: s:stdlib, t:tweak

#1871 Fix a bug that caused compilation error if a defer node was used in a feedback loop without an upstream error raiser
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/src/templates.js
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
Labels: hotfix, regression, s:core

#1869 Fix updating of package indexes and bundle the last one
  packages/xod-client-electron/src/arduinoDependencies/components/UpdateArduinoPackagesPopup.jsx
  packages/xod-client-electron/src/arduinoDependencies/runners.js
  packages/xod-client-electron/src/upload/arduinoCli.js
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
  workspace/__packages__/package_index.json
Labels: hotfix

#1875 Fix quickstart node for 20x4 I2C text LCD
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-20x4/patch.xodp
Labels: hotfix

#1877 Fix dht library
  workspace/__lib__/xod-dev/dht/dhtxx-read-raw/patch.cpp
  workspace/__lib__/xod-dev/dht/read(dht2x-device)/patch.xodp
  workspace/__lib__/xod-dev/dht/unpack-dht2x-device/patch.xodp
Labels: hotfix

#1873 Improve error propagation through defer nodes
  packages/xod-arduino/platform/patchContext.tpl.cpp
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/platform/runtime.cpp
  workspace/__lib__/xod/core/defer(boolean)/patch.cpp
  workspace/__lib__/xod/core/defer(byte)/patch.cpp
  workspace/__lib__/xod/core/defer(number)/patch.cpp
  workspace/__lib__/xod/core/defer(pulse)/patch.cpp
  workspace/__lib__/xod/core/defer(string)/patch.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/test/test-core/test-feedback-loops/patch.test.tsv
  workspace/test/test-core/test-feedback-loops/patch.xodp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: hotfix, s:core

#1880 Fix debounce in the button node
  workspace/__lib__/xod/common-hardware/button/patch.xodp
Labels: hotfix

#1878 Update changelog for upcoming 0.31.1
  CHANGELOG.md
Labels: s:doc, t:chore

#1881 Release 0.31.1
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1883 Merge 0.31.x into master
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-arduino/platform/patchContext.tpl.cpp
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/platform/runtime.cpp
  packages/xod-arduino/src/templates.js
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/arduinoDependencies/components/UpdateArduinoPackagesPopup.jsx
  packages/xod-client-electron/src/arduinoDependencies/runners.js
  packages/xod-client-electron/src/upload/arduinoCli.js
  packages/xod-client-electron/src/upload/components/PopupUploadConfig.jsx
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/dht/dhtxx-read-raw/patch.cpp
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/dht/read(dht2x-device)/patch.xodp
  workspace/__lib__/xod-dev/dht/unpack-dht2x-device/patch.xodp
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-20x4/patch.xodp
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/button/patch.xodp
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/defer(boolean)/patch.cpp
  workspace/__lib__/xod/core/defer(byte)/patch.cpp
  workspace/__lib__/xod/core/defer(number)/patch.cpp
  workspace/__lib__/xod/core/defer(pulse)/patch.cpp
  workspace/__lib__/xod/core/defer(string)/patch.cpp
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__packages__/package_index.json
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/test/test-core/test-feedback-loops/patch.test.tsv
  workspace/test/test-core/test-feedback-loops/patch.xodp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: t:chore

#1890 Upkeep README and CONTRIBUTING
  .github/xoding.gif
  CONTRIBUTING.md
  README.md
  tools/xod-jetbrains-live-template/xod-jetbrains-live-template.jar
  tools/xod-jetbrains-live-template/xod-jetbrains-live-template.md
Labels: s:infra, t:doc

#1894 Show error message about missing value for global literal preperly
  packages/xod-client-electron/src/view/formatError.js
Labels: s:client, t:bug

#1893 Make possible to generate/set API key for the project within IDE
  packages/xod-client/src/core/containers/App.jsx
  packages/xod-client/src/project/actionTypes.js
  packages/xod-client/src/project/actions.js
  packages/xod-client/src/project/components/PopupProjectPreferences.jsx
  packages/xod-client/src/project/messages.js
  packages/xod-client/src/project/reducer.js
  packages/xod-client/src/project/state.js
  packages/xod-client/src/user/actions.js
  packages/xod-client/src/utils/urls.js
  packages/xod-client/test/hinting.spec.js
  packages/xod-client/test/project.spec.js
  packages/xod-fs/src/convertTypes.js
  packages/xod-fs/test/load.spec.js
  packages/xod-project/src/optionalFieldsUtils.js
  packages/xod-project/src/project.js
  packages/xod-project/src/types.js
  packages/xod-project/test/fixtures/with-empty-optional-fields.xodball
  packages/xod-project/test/helpers.js
Labels: s:client, s:core, t:feat
