Repository xodio/xod, pull requests merged in 2019-09, with the labels that each got.

#1838 Add `xod/json` library
  workspace/__lib__/xod/debug/stream-string/patch.cpp
  workspace/__lib__/xod/debug/stream-string/patch.xodp
  workspace/__lib__/xod/json/0-example/patch.xodp
  workspace/__lib__/xod/json/boolean-value/patch.cpp
  workspace/__lib__/xod/json/boolean-value/patch.xodp
  workspace/__lib__/xod/json/key/patch.cpp
  workspace/__lib__/xod/json/key/patch.xodp
  workspace/__lib__/xod/json/nth/patch.cpp
  workspace/__lib__/xod/json/nth/patch.xodp
  workspace/__lib__/xod/json/number-value/patch.cpp
  workspace/__lib__/xod/json/number-value/patch.xodp
  workspace/__lib__/xod/json/parse-json/patch.cpp
  workspace/__lib__/xod/json/parse-json/patch.xodp
  workspace/__lib__/xod/json/parsed-json-chunk/patch.cpp
  workspace/__lib__/xod/json/parsed-json-chunk/patch.xodp
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/json/string-value/patch.cpp
  workspace/__lib__/xod/json/string-value/patch.xodp
  workspace/__lib__/xod/net/http-get-json/patch.xodp
  workspace/__lib__/xod/net/http-response-body/patch.xodp
  workspace/test/test-json-parser/project.xod
  workspace/test/test-json-parser/test-booleans/patch.test.tsv
  workspace/test/test-json-parser/test-booleans/patch.xodp
  workspace/test/test-json-parser/test-nested-arrays/patch.test.tsv
  workspace/test/test-json-parser/test-nested-arrays/patch.xodp
  workspace/test/test-json-parser/test-nested-objects/patch.test.tsv
  workspace/test/test-json-parser/test-nested-objects/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-array/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-array/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-false/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-false/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-key/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-key/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-null/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-null/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-true/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-true/patch.xodp
  workspace/test/test-json-parser/test-raise-error-on-invalid-value/patch.test.tsv
  workspace/test/test-json-parser/test-raise-error-on-invalid-value/patch.xodp
  workspace/test/test-json-parser/test-reparsing/patch.test.tsv
  workspace/test/test-json-parser/test-reparsing/patch.xodp
Labels: s:stdlib, t:feat

#1835 On the way to following new hardware guidlines
  workspace/__lib__/xod-dev/pn532-nfc/example-nfc-scanner/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/example-read-page/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/example-tickets/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/example-write-page/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/init/patch.cpp
  workspace/__lib__/xod-dev/pn532-nfc/init/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/input-pn532-device/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/is-empty/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/nfc-scanner/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/nfc-uid/patch.cpp
  workspace/__lib__/xod-dev/pn532-nfc/output-pn532-device/patch.xodp
  workspace/__lib__/xod-dev/pn532-nfc/pair-tag/patch.cpp
  workspace/__lib__/xod-dev/pn532-nfc/pn532-device/patch.cpp
  workspace/__lib__/xod-dev/pn532-nfc/validate-uid/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/clear(text-lcd-i2c-device)/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/clear(text-lcd-i2c-device)/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/clear(text-lcd-parallel-device)/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/clear(text-lcd-parallel-device)/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/clear/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/example-i2c-print/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/example-parallel-print/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/example-print-at/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/example-quick-start/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/print-at(text-lcd-i2c-device)/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/print-at(text-lcd-i2c-device)/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/print-at(text-lcd-parallel-device)/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/print-at(text-lcd-parallel-device)/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/print-at/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/text-lcd/set-backlight/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/set-backlight/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-16x2/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-20x4/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-device/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-i2c-device/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-parallel-16x2/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-parallel-20x4/patch.xodp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-parallel-device/patch.cpp
  workspace/__lib__/xod-dev/text-lcd/text-lcd-parallel-device/patch.xodp
  workspace/__lib__/xod/common-hardware/relay/patch.xodp
  workspace/__lib__/xod/common-hardware/text-lcd-16x2-i2c/patch.xodp
  workspace/__lib__/xod/common-hardware/text-lcd-16x2/patch.xodp
  workspace/__lib__/xod/core/act/patch.xodp
  workspace/__lib__/xod/core/overrun/patch.xodp
  workspace/__lib__/xod/core/pulse-on-change(boolean)/patch.cpp
  workspace/__lib__/xod/core/pulse-on-change(boolean)/patch.test.tsv
  workspace/__lib__/xod/core/pulse-on-change(boolean)/patch.xodp
  workspace/__lib__/xod/core/pulse-on-true/patch.cpp
  workspace/__lib__/xod/core/wait-all-once/patch.xodp
  workspace/__lib__/xod/core/wait-all/patch.xodp
  workspace/welcome-to-xod/108-text-lcd/patch.xodp
  workspace/welcome-to-xod/109-thermometer/patch.xodp
  workspace/welcome-to-xod/209-slow-down/patch.xodp
  workspace/welcome-to-xod/210-string-formatting/patch.xodp
  workspace/welcome-to-xod/211-units-of-measure/patch.xodp
Labels: s:stdlib

#1842 Replace UPDs with ACTs on idempotent actuators
  workspace/__lib__/xod-dev/servo/servo/patch.xodp
  workspace/__lib__/xod/common-hardware/h-bridge-dc-motor/patch.xodp
  workspace/__lib__/xod/common-hardware/led/patch.xodp
Labels: breaking, s:stdlib

#1846 Add digital-read with pull-up
  workspace/__lib__/xod/common-hardware/button/patch.xodp
  workspace/__lib__/xod/gpio/digital-read-pullup/patch.cpp
  workspace/__lib__/xod/gpio/digital-read-pullup/patch.xodp
Labels: s:stdlib, t:feat

#1852 Fix tweak nodes behaviour bug
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/src/templates.js
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: regression

#1845 Add missing “files” fileds in package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
Labels: s:infra, t:chore
