Repository xodio/xod, pull requests merged in 2019-07, with the labels that each got.

#1815 Make servo pulse limits match Arduino defaults
  workspace/__lib__/xod-dev/servo/servo-device/patch.xodp
Labels: s:stdlib, t:tweak

#1821 Fix sending data from the nested tweaks
  packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js
  packages/xod-client/src/debugger/selectors.js
  packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
Labels: s:client, t:bug

#1816 Respect serial.disableRTS option from boards.txt when opening serialport for debugging
  packages/arduino-cli/src/optionParser.js
  packages/arduino-cli/test-func/index.spec.js
  packages/arduino-cli/test/fixtures/packages/fictional/hardware/fake/1.2.3/boards.txt
  packages/arduino-cli/test/optionParser.spec.js
  packages/xod-client-electron/src/app/arduinoActions.js
  packages/xod-client-electron/src/app/main.js
  packages/xod-client-electron/src/debugger/ipcActions.js
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-deploy/src/serialport.js
Labels: s:client

#1823 Remove one stale mention of error code from `i2c/read-byte`
  workspace/__lib__/xod/i2c/read-byte/patch.xodp
Labels: s:stdlib

#1824 Release 0.30.0
  CHANGELOG.md
  lerna.json
  packages/arduino-cli/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-func-tools/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1825 Fix and add nodes that works with errored pulses
  workspace/__lib__/xod/core/error(pulse)/patch.cpp
  workspace/__lib__/xod/core/has-error(pulse)/patch.cpp
  workspace/__lib__/xod/core/has-error(pulse)/patch.xodp
  workspace/__lib__/xod/core/if-error(pulse)/patch.cpp
  workspace/__lib__/xod/core/if-error(pulse)/patch.xodp
Labels: hotfix, s:stdlib

#1827 Fix library publishing
  packages/xod-client/src/user/actions.js
Labels: hotfix, regression, s:client

#1828 Release 0.30.1
  CHANGELOG.md
  lerna.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1830 Merge 0.30.x into master
  CHANGELOG.md
  lerna.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-client/src/user/actions.js
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/error(pulse)/patch.cpp
  workspace/__lib__/xod/core/has-error(pulse)/patch.cpp
  workspace/__lib__/xod/core/has-error(pulse)/patch.xodp
  workspace/__lib__/xod/core/if-error(pulse)/patch.cpp
  workspace/__lib__/xod/core/if-error(pulse)/patch.xodp
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore
