Repository xodio/xod, pull requests merged in 2020-09, with the labels that each got.

#2027 Fix follow log in Debugger pane
  packages/xod-client/src/debugger/actions.js
  packages/xod-client/src/debugger/containers/Log.jsx
  packages/xod-client/src/debugger/reducer.js
  packages/xod-client/src/editor/reducer.js
  packages/xod-client/src/utils/components/Autoscroll.jsx
  packages/xod-client/stories/Debugger.jsx
Labels: s:client, t:bug

#2011 Make color-type outputs bindable
  packages/xod-client/src/editor/containers/Patch/modes/selecting.jsx
  packages/xod-client/src/project/components/Node.jsx
  packages/xod-project/src/index.js
  packages/xod-project/src/patch.js
Labels: s:client, s:core, t:tweak

#2029 Update bundled arduino-cli to 0.12.0
  .circleci/config.yml
  packages/arduino-cli/src/index.js
  packages/xod-cli/test-func/compile-upload.spec.js
  packages/xod-client-electron/src/app/main.js
  packages/xod-deploy-bin/src/messages.js
  tools/install-arduinocli.ps1
Labels: s:infra

#2038 Support esp32 boards
  .prettierignore
  packages/xod-deploy-bin/src/arduinoCli.js
  workspace/__ardulib__/ESP32Servo/.gitignore
  workspace/__ardulib__/ESP32Servo/README.md
  workspace/__ardulib__/ESP32Servo/examples/Knob/Knob.ino
  workspace/__ardulib__/ESP32Servo/examples/Multiple-Servo-Example-Arduino/Multiple-Servo-Example-Arduino.ino
  workspace/__ardulib__/ESP32Servo/examples/PWMExample/PWMExample.ino
  workspace/__ardulib__/ESP32Servo/examples/Sweep/Sweep.ino
  workspace/__ardulib__/ESP32Servo/examples/ToneExample/ToneExample.ino
  workspace/__ardulib__/ESP32Servo/examples/analogWriteExample/analogWriteExample.ino
  workspace/__ardulib__/ESP32Servo/keywords.txt
  workspace/__ardulib__/ESP32Servo/library.properties
  workspace/__ardulib__/ESP32Servo/src/ESP32PWM.cpp
  workspace/__ardulib__/ESP32Servo/src/ESP32PWM.h
  workspace/__ardulib__/ESP32Servo/src/ESP32Servo.cpp
  workspace/__ardulib__/ESP32Servo/src/ESP32Servo.h
  workspace/__ardulib__/ESP32Servo/src/ESP32Tone.cpp
  workspace/__ardulib__/ESP32Servo/src/ESP32Tone.h
  workspace/__ardulib__/ESP32Servo/src/analogWrite.cpp
  workspace/__ardulib__/ESP32Servo/src/analogWrite.h
  workspace/__ardulib__/README.md
  workspace/__lib__/xod-dev/servo/servo-device/patch.cpp
  workspace/__lib__/xod/gpio/pwm-write/patch.cpp
  workspace/big-patch/__fixtures__/arduino.cpp
Labels: s:client, s:stdlib

#2040 Fix hotkeys in Inspector Pin widgets
  packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
Labels: s:client, t:bug

#2041 Fix tweak-bytes: make possible to use char literals in live session
  packages/xod-arduino/src/formatTweakMessage.js
  packages/xod-project/src/utils.js
Labels: s:core, t:bug

#2042 Copy values bound to `tweak-string`s directly into buffers
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/src/templates.js
  workspace/__lib__/xod/debug/tweak-string-128/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-16/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-32/patch.cpp
  workspace/__lib__/xod/debug/tweak-string-64/patch.cpp
  workspace/big-patch/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/dht-pack-unpack/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: hotfix

#2039 chore(infra): release 0.35.2
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
Labels: hotfix

#2045 Add information about constants in C++ Cheatsheet (sidebar)
  packages/xod-client/src/core/styles/components/CppPatchDocs.scss
  packages/xod-client/src/editor/components/CppPatchDocs.jsx
  packages/xod-project/src/utils.js
Labels: s:client, t:tweak

#2048 Fix dirtyness propagation optimization to work fine with tweaks
  packages/xod-arduino/platform/program.tpl.cpp
  packages/xod-arduino/src/templates.js
Labels: hotfix, s:rt/c++

#2049 chore(infra): release 0.35.3
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
Labels: hotfix
