Repository xodio/xod, pull requests merged in 2020-02, with the labels that each got.

#1952 Mark compiled fixtures as generated
  .gitattributes
Labels: s:infra, t:tweak

#1934 Support of ST7735 based TFT displays
  workspace/__ardulib__/README.md
  workspace/__ardulib__/ST7735/XST7735.cpp
  workspace/__ardulib__/ST7735/XST7735.h
  workspace/__lib__/xod-dev/st7735-display/init-b/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/init-b/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/init-g/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/init-g/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/init-rg/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/init-rg/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/init-rr/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/init-rr/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/st7735-display/render/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/render/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-b-device/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-b/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-g-device/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-g/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rg-device/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rg/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rr-device/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735-128x160-rr/patch.xodp
  workspace/__lib__/xod-dev/st7735-display/st7735/patch.cpp
  workspace/__lib__/xod-dev/st7735-display/st7735/patch.xodp
Labels: s:stdlib

#1953 Add color picker widget
  packages/xod-client-electron/src/debugger/sendToSerialMiddleware.js
  packages/xod-client/package.json
  packages/xod-client/src/core/styles/components/ColorPicker.scss
  packages/xod-client/src/core/styles/components/CustomScroll.scss
  packages/xod-client/src/core/styles/components/Helpbox.scss
  packages/xod-client/src/core/styles/components/Inspector.scss
  packages/xod-client/src/core/styles/components/PointingPopup.scss
  packages/xod-client/src/core/styles/main.scss
  packages/xod-client/src/debugger/sendToSimulationSerialMiddleware.js
  packages/xod-client/src/editor/actionTypes.js
  packages/xod-client/src/editor/actions.js
  packages/xod-client/src/editor/components/ColorPicker/HueCircle.jsx
  packages/xod-client/src/editor/components/ColorPicker/SatLightBox.jsx
  packages/xod-client/src/editor/components/ColorPicker/colorPropType.js
  packages/xod-client/src/editor/components/ColorPicker/index.jsx
  packages/xod-client/src/editor/components/PointingPopup.jsx
  packages/xod-client/src/editor/components/SidebarPanel.jsx
  packages/xod-client/src/editor/components/Suggester.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/ColorPickerWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/Widget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/index.js
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/ColorPinWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/PinWidget.jsx
  packages/xod-client/src/editor/constants.js
  packages/xod-client/src/editor/containers/Helpbox.jsx
  packages/xod-client/src/editor/reducer.js
  packages/xod-client/src/editor/selectors.js
  packages/xod-client/src/editor/state.js
  packages/xod-client/src/editor/utils.js
  packages/xod-client/src/hinting/patchSearchData.js
  packages/xod-client/src/hinting/typeDeduction.js
  packages/xod-client/src/hinting/validation.js
  packages/xod-client/src/index.js
  packages/xod-client/src/project/actionTypes.js
  packages/xod-client/src/project/actions.js
  packages/xod-client/src/project/components/nodeParts/NodeLabel.jsx
  packages/xod-client/src/project/reducer.js
  packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
  packages/xod-client/stories/ColorPicker.jsx
  packages/xod-client/test/hinting.spec.js
  yarn.lock
Labels: s:client, t:feat

#1962 Fix the scanline boundary condition for the canvas rendering process.
  workspace/__ardulib__/Graphics/XGraphics.inl
Labels: s:stdlib

#1961 Fix up the RST pin conditions and the assertion in the ST7735 display library.
  workspace/__ardulib__/ST7735/XST7735.cpp
  workspace/__lib__/xod-dev/st7735-display/st7735/patch.cpp
Labels: s:stdlib

#1963 Fix throttle node: pass the constant values on setting up
  workspace/__lib__/xod/core/throttle/patch.cpp
  workspace/test/test-core/test-throttle-numbers/patch.test.tsv
Labels: s:stdlib, t:bug

#1960 Update changelog for the upcoming v0.33.0
  CHANGELOG.md
Labels: t:chore

#1965 Release 0.33.0
  CHANGELOG.md
  lerna.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
Labels: t:chore

#1966 Upgrade bs-platform to 7.1.1
  bsconfig.json
  packages/belt-holes/bsconfig.json
  packages/belt-holes/package.json
  packages/belt-holes/test/BeltHoles_List_jest.re
  packages/xod-arduino/bsconfig.json
  packages/xod-arduino/package.json
  packages/xod-client-electron/package.json
  packages/xod-func-tools/bsconfig.json
  packages/xod-func-tools/package.json
  packages/xod-func-tools/src/Either.re
  packages/xod-func-tools/src/Errors.re
  packages/xod-func-tools/src/Maybe.re
  packages/xod-project/bsconfig.json
  packages/xod-project/package.json
  packages/xod-project/src/PatchPath.re
  packages/xod-tabtest/bsconfig.json
  packages/xod-tabtest/package.json
  yarn.lock
Labels: s:infra, t:chore

#1967 Add tool for publishing stdlib
  tools/publish-stdlib.sh
Labels: s:infra, t:tweak

#1971 Fix positioning of the ColorPicker widget with right-sided Inspector
  packages/xod-client/src/core/styles/components/PointingPopup.scss
  packages/xod-client/src/editor/components/inspectorWidgets/ColorPickerWidget.jsx
  packages/xod-client/src/editor/components/inspectorWidgets/pinWidgets/ColorPinWidget.jsx
Labels: hotfix, s:client

#1972 Fix scrolling of Project Browser and Inspector when they are alone in sidebar
  packages/xod-client/src/core/assets/index.html
  packages/xod-client/src/core/styles/components/Editor.scss
  packages/xod-client/src/core/styles/components/Inspector.scss
  packages/xod-client/src/core/styles/components/ProjectBrowser.scss
Labels: s:client, t:bug
