Repository xodio/xod, pull requests merged in 2020-06, with the labels that each got.

#1994 Fix compiling of WS2812 on ESP8266
  workspace/__ardulib__/WS2812_NoBufffer/WS2812.inl
Labels: s:stdlib, t:bug

#1995 Fix an uncaught exception when transpiling a patch with a “dangling” defer node
  packages/xod-arduino/src/templates.js
Labels: s:core, t:bug

#1999 Clone patch feature
  packages/xod-client/src/hinting/middleware.js
  packages/xod-client/src/hinting/patchMarkers.js
  packages/xod-client/src/hinting/validation.js
  packages/xod-client/src/project/actionTypes.js
  packages/xod-client/src/project/actions.js
  packages/xod-client/src/project/messages.js
  packages/xod-client/src/project/reducer.js
  packages/xod-client/src/projectBrowser/components/PatchGroupItemContextMenu.jsx
  packages/xod-client/src/projectBrowser/containers/ProjectBrowser.jsx
  packages/xod-project/src/messages.js
  packages/xod-project/src/project.js
  packages/xod-project/test/project.spec.js
Labels: s:client, s:core, t:feat

#1986 Updating arduino-cli to 0.10
  .circleci/config.yml
  packages/arduino-cli/README.md
  packages/arduino-cli/src/config.js
  packages/arduino-cli/src/index.js
  packages/arduino-cli/src/optionParser.js
  packages/arduino-cli/test-func/index.spec.js
  packages/arduino-cli/test/optionParser.spec.js
  packages/xod-cli/test-func/installArch.spec.js
  packages/xod-deploy-bin/src/arduinoCli.js
  tools/install-arduinocli.ps1
Labels: wip

#2003 Fixed cloning of specialization patches
  packages/xod-project/src/internal/patchPathUtils.js
  packages/xod-project/src/patchPathUtils.js
  packages/xod-project/src/project.js
  packages/xod-project/test/project.spec.js
Labels: s:core, t:bug
