Repository xodio/xod, pull requests merged in 2020-08, with the labels that each got.

#2008 Fix creating cast nodes for custom types
  packages/xod-project/src/flatten.js
  packages/xod-project/src/patchPathUtils.js
  packages/xod-project/test/fixtures/cast-custom-types.xodball
  packages/xod-project/test/flatten.spec.js
Labels: s:core, t:bug

#2006 Fix forward declaration of HardwareSerial for megaAVR architecture
  packages/xod-arduino/platform/uart.h
  workspace/big-patch/__fixtures__/arduino.cpp
  workspace/blink/__fixtures__/arduino.cpp
  workspace/count-with-feedback-loops/__fixtures__/arduino.cpp
  workspace/lcd-time/__fixtures__/arduino.cpp
  workspace/two-button-switch/__fixtures__/arduino.cpp
Labels: s:rt/c++

#2012 Support arduino-cli v0.11.0
  packages/arduino-cli/src/index.js
Labels: t:bug

#2024 Add missing dependency for xod-dev/pn532-nfc
  workspace/__lib__/xod-dev/pn532-nfc/pn532-device/patch.cpp
Labels: s:stdlib, t:bug

#2025 Fix flatten: get rid of stale output custom type terminals
  packages/xod-project/src/flatten.js
  packages/xod-project/test/fixtures/cast-custom-types.xodball
  packages/xod-project/test/flatten.spec.js
Labels: s:core, t:bug

#2026 Use upstream ESP8266 package index instead of locked v2.4.3
  packages/xod-deploy-bin/src/arduinoCli.js
  packages/xod-deploy-bin/src/constants.js
Labels: s:cli, s:client, t:feat
