Repository xodio/xod, pull requests merged in 2021-01, with the labels that each got.

#2083 Merge 0.36.x into master
  CHANGELOG.md
  lerna.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/animation-unit/patch.cpp
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/is-receiving/patch.cpp
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
  workspace/welcome-to-xod/001-hello/patch.xodp
Labels: t:chore

#2082 Fix workspace errors when user deleted a workspace
  packages/xod-cli/src/commands/boards.js
  packages/xod-cli/src/listrTasks.js
  packages/xod-client-electron/src/app/arduinoCli.js
  packages/xod-deploy-bin/package.json
  packages/xod-deploy-bin/src/arduinoCli.js
Labels: t:bug

#2084 Move to Electron v10, node.js v12
  .circleci/Dockerfile
  .circleci/config.yml
  .nvmrc
  appveyor.yml
  package.json
  packages/arduino-cli/.babelrc
  packages/xod-cli/.babelrc
  packages/xod-cli/src/commands/upload.js
  packages/xod-client-browser/benchmark/.babelrc
  packages/xod-client-browser/test-func/.babelrc
  packages/xod-client-electron/.babelrc
  packages/xod-client-electron/package.json
  packages/xod-client-electron/src/app/arduinoActions.js
  packages/xod-client-electron/src/app/main.js
  packages/xod-client-electron/src/app/settings.js
  packages/xod-client-electron/src/app/utils.js
  packages/xod-client-electron/src/settings/components/PopupSetWorkspace.jsx
  packages/xod-client-electron/src/shared/errorFormatter.js
  packages/xod-client-electron/src/upload/components/PortSelect.jsx
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client-electron/test-func/0-fs.spec.js
  packages/xod-client-electron/test-func/pageObject.js
  packages/xod-client-electron/test-func/prepare.js
  packages/xod-client-electron/test/mocha.opts
  packages/xod-client-electron/webpack.config.js
  packages/xod-deploy-bin/.babelrc
  packages/xod-deploy-bin/src/arduinoCli.js
  packages/xod-deploy/.babelrc
  packages/xod-deploy/package.json
  packages/xod-deploy/src/serialport.js
  packages/xod-fs/.babelrc
  packages/xod-patch-search/.babelrc
  packages/xod-pm/.babelrc
  packages/xod-tabtest/src/Tabtest.re
  tools/spectron-repl
  yarn.lock
Labels: s:infra

#2074 Recover IDE from runtime exceptions in renderer process
  .circleci/cache-version
  packages/xod-client-browser/package.json
  packages/xod-client-browser/src/containers/App.jsx
  packages/xod-client-browser/test-func/bootstrap.js
  packages/xod-client-browser/test-func/creatingBlinkPatch.spec.js
  packages/xod-client-browser/test-func/mocha.opts
  packages/xod-client-browser/test-func/pageObjects/IdeCrashReport.js
  packages/xod-client-browser/test-func/pageObjects/Node.js
  packages/xod-client-browser/test-func/recovering.spec.js
  packages/xod-client-browser/test-func/server.config.js
  packages/xod-client-browser/test-func/utils/getPage.js
  packages/xod-client-browser/webpack.config.test.js
  packages/xod-client-electron/src/view/containers/App.jsx
  packages/xod-client/src/core/actionTypes.js
  packages/xod-client/src/core/actions.js
  packages/xod-client/src/core/containers/App.jsx
  packages/xod-client/src/core/containers/Catcher.jsx
  packages/xod-client/src/core/containers/Root.jsx
  packages/xod-client/src/core/reducer.js
  packages/xod-client/src/core/styles/components/IdeCrashReport.scss
  packages/xod-client/src/core/styles/main.scss
  packages/xod-client/src/hinting/patchSearchData.js
  packages/xod-client/src/hinting/typeDeduction.js
  packages/xod-client/src/hinting/validation.js
  packages/xod-client/src/messages/containers/SnackBar.jsx
  yarn.lock
Labels: s:client, t:feat

#2085 Update changelog for the upcoming v0.37.0
  CHANGELOG.md
Labels: t:chore

#2086 Release 0.37.0
  CHANGELOG.md
  lerna.json
  packages/arduino-cli/package.json
  packages/xod-arduino/package.json
  packages/xod-cli/package.json
  packages/xod-client-browser/package.json
  packages/xod-client-electron/package.json
  packages/xod-client/package.json
  packages/xod-cloud-compile/package.json
  packages/xod-deploy-bin/package.json
  packages/xod-deploy/package.json
  packages/xod-fs/package.json
  packages/xod-patch-search/package.json
  packages/xod-pm/package.json
  packages/xod-project/package.json
  packages/xod-tabtest/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
Labels: t:chore

#2087 Fix: configure electron-settings for all kinds of processes
  packages/xod-client-electron/src/app/main.js
  packages/xod-client-electron/src/app/settings.js
  packages/xod-client-electron/src/app/utils.js
Labels: regression, t:bug

#2088 Release 0.37.1
  CHANGELOG.md
  lerna.json
  packages/xod-client-electron/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
Labels: t:chore

#2091 Release 0.37.2
  CHANGELOG.md
  lerna.json
  packages/xod-client-electron/package.json
  workspace/__lib__/xod-cloud/basics/project.xod
  workspace/__lib__/xod-cloud/feeds/project.xod
  workspace/__lib__/xod-dev/dht/project.xod
  workspace/__lib__/xod-dev/ds-rtc/project.xod
  workspace/__lib__/xod-dev/esp8266-mcu/project.xod
  workspace/__lib__/xod-dev/esp8266/project.xod
  workspace/__lib__/xod-dev/hc-sr04/project.xod
  workspace/__lib__/xod-dev/pn532-nfc/project.xod
  workspace/__lib__/xod-dev/servo/project.xod
  workspace/__lib__/xod-dev/sharp-irm/project.xod
  workspace/__lib__/xod-dev/ssd1306-display/project.xod
  workspace/__lib__/xod-dev/st-mems/project.xod
  workspace/__lib__/xod-dev/st7735-display/project.xod
  workspace/__lib__/xod-dev/text-lcd/project.xod
  workspace/__lib__/xod-dev/w5500/project.xod
  workspace/__lib__/xod-dev/ws2812/project.xod
  workspace/__lib__/xod/bits/project.xod
  workspace/__lib__/xod/color/project.xod
  workspace/__lib__/xod/common-hardware/project.xod
  workspace/__lib__/xod/core/project.xod
  workspace/__lib__/xod/datetime/project.xod
  workspace/__lib__/xod/debug/project.xod
  workspace/__lib__/xod/gpio/project.xod
  workspace/__lib__/xod/graphics/project.xod
  workspace/__lib__/xod/i2c/project.xod
  workspace/__lib__/xod/json/project.xod
  workspace/__lib__/xod/math/project.xod
  workspace/__lib__/xod/mutex/project.xod
  workspace/__lib__/xod/net/project.xod
  workspace/__lib__/xod/stream/project.xod
  workspace/__lib__/xod/uart/project.xod
  workspace/__lib__/xod/units/project.xod
  workspace/__lib__/xod/waves/project.xod
Labels: t:chore

#2094 Remove AppVeyor badge
  README.md
Labels: t:chore

#2093 Pin node versions in CircleCI runners.
  .circleci/Dockerfile
  .circleci/config.yml
  .nvmrc
  package.json
  tools/match-node-version-to-electron.js
Labels: s:infra

#2095 Change base of CircleCI docker image
  .circleci/Dockerfile
  .circleci/cache-version
  .circleci/config.yml
Labels: s:infra, t:tweak
